### ISSUE TITLE
Enahacement for use in eCommerce Sites

### ISSUE THREAD

**Issue by pbanks** [jessepollak/card#109]
1.       All payment processors require the date to be in the format of a 2 field MM and YYYY – they and most eCommerce packages cannot distinguish your output of MMYY. So it would be great if you had an “output” ability for TWO separate fields that could be parsed to a form.
2.       Whilst Credit Cards “show” their Numbers in 4-digit blocks (except Amex, of course) ALL credit card processors require a complete numeric string with NO spaces or dashes etc. So, whilst your program screen output “looks” the same as a credit card it would be TOTALLY useful to strip out all the spaces when parsing to a form.

**Comment by gbossss** [comment]
agree.

**Comment by jessepollak** [comment]
Thanks for your feedback! 

Card doesn't handle output, only display. If you'd like to get the data out of the fields in a different manner, you should be able to access the inputs and get their values in whatever form you want.

Closing this issue — if you have any other questions, let me know!
