### ISSUE TITLE
Make card responsive

### ISSUE THREAD

**Issue by scttdavs** [jessepollak/card#115]
This would be a great enhancement. Right now it's not responsive.

It does apply the ```transform: scale()``` to the container, so listening for screen widths and adjusting that scale with javascript does the trick for now. But it's a little hacky, since it's position is relative, that needs to be adjusted as well.

Would be great if it were responsive right out the box, or at least an option to turn on.

**Comment by marclennox** [comment]
@scttdavs Any chance you can post a gist of your resize code in the meantime?

**Comment by sebrojas14** [comment]
Please!

**Comment by jessepollak** [comment]
Thank you all for your time, thought, and feedback!

Here's my basic thinking:

* I don't think the CSS of the Card faces can be made fully responsive. So much of the design is pixel-perfect and I'm not sure I can recreate it in a flexible manner (or at least not with a huge time commitment). This is why the `transform: scale` logic is there, it's just too hard to do it any other way.
* Given that the library doesn't know how Card is used on a page, I don't think it can create a responsive scaling default that works effectively. How wide is your Card to start? When do you want to scale it down? All those are questions the library can't really answer.
* The above two thoughts led me to the conclusion that responsiveness should be handled at the media query level by the user. Anyone can use media queries to apply the same `transform: scale` styling I do in the width logic.

To that end, I'm closing this issue for now. If anyone has additional thoughts, please comment below — happy to reconsider!
