### ISSUE TITLE
Add some scandanavian love in there

### ISSUE THREAD

**Issue by kfwerf** [jessepollak/card#124]
Hey, ive checked out the more recent version of cardjs and noticed it needs few more keys in the allowed Symbols. Scandanavians have a longer vocabulary and with that in mind have å, ö, ä (219, 186, 222).

Can you add:

    219, 186, 222 # å, ö, ä (when not using shiftKey)

on line 225 of card.coffee? I would add it myself but my build system is messed up so i cant commit it properly. It should be added the the allowSymbol array.

E.g. 

    allowedSymbols = [
        189, 109 # hyphen (when not using shiftKey)
        190, 110 # dot (when not using shiftKey)
        222, 186, 219 # å, ä, ö (when not using shiftKey)
      ]

around line 222

Cheers! Ive added it on my end and it seems to function!

**Comment by mirorauhala** [comment]
Yep, I'd like the same functionality. Otherwise useless here in Finland

**Comment by jessepollak** [comment]
The character restriction for the name will be removed in v1.0.0 so I'm closing this! Thanks!

**Comment by mirorauhala** [comment]
Wohooo ! WinWin for all :dancer:
