### ISSUE TITLE
Turkish Char Uppercase 

### ISSUE THREAD

**Issue by alpcnet** [jessepollak/card#139]
Please Add your script this code .

// Added following lines to 304 - 305 lines for version 1.0.0
var letters = { "İ": "[İi]", "I": "[Iı]", "Ş": "[Şş]", "Ğ": "[Ğğ]", "Ü": "[Üü]", "Ö": "[Öö]", "Ç": "[Çç]", "i": "[İi]", "ı": "[Iı]", "ş": "[Şş]", "ğ": "[Ğğ]", "ü": "[Üü]", "ö": "[Öö]", "ç": "[Çç]" };
escapedSearchText = escapedSearchText.replace(/(([İIŞĞÜÇÖiışğüçö]))/g, function(letter){ return letters[letter]; });

**Comment by jessepollak** [comment]
The character restriction on the name will be removed in 1.0.0, so I'm closing this!
