### ISSUE TITLE
any validation provided  ?

### ISSUE THREAD

**Issue by pociej** [jessepollak/card#144]
Is here any methods for fields validation on submit(). Probably i missed something but there is nothing about in docs.

**Comment by vietqhoang** [comment]
I know this isn't ideal, but it is an option. Stripe has an excellent validation library which can be used in conjunction with card.js.

The library is located below:
https://github.com/stripe/jquery.payment

**Comment by jessepollak** [comment]
You can use [Payment](https://github.com/jessepollak/payment) or [jquery.payment](https://github.com/stripe/jquery.payment) to do validation - Card doesn't provide this.
