### ISSUE TITLE
Clear the form after response

### ISSUE THREAD

**Issue by ideiadeweb** [jessepollak/card#148]
Hey guys,

I can't seem to find a way to clear the card data from the image after a jquery response.

I can clear the values from my inputs, but the card-info stays in the image (which according to Cielo is against PCI regulations).

Is there a way to sorta reset the plugin?

Screenshot: http://prntscr.com/5xo7uf

**Comment by jessepollak** [comment]
Thanks for reporting this issue!

You can clear the Card form by change the values of the inputs to blank and then triggering paste on them. Right now, there is known issue with triggering with jQuery (#170) — that should be fixed soon or you can follow the workaround there.
