### ISSUE TITLE
when passing masked card number "4111**********11" as values.number no card type is recognized

### ISSUE THREAD

**Issue by alekbarszczewski** [jessepollak/card#153]
card.js does not recognize CC type (VISA/MasterCard/etc) when masked number is provided.

**Comment by sebrojas14** [comment]
I think your issue is not clrear enough

**Comment by jessepollak** [comment]
Thanks for reporting this issue, much appreciated!

So, the `values` initializer isn't what this is for. Rather, it's for specifying the default values that show up on the card before users add data. The best analogy for this is the `placeholder` attribute on an input.

What you're looking for is the ability to pass in actual values that will Card will be initialized with. I've created a new issue for that at #184, so I'm closing this issue for now. Would appreciate any feedback there!
