### ISSUE TITLE
404 on jessepollak/card/master/lib/css/card.css

### ISSUE THREAD

**Issue by kytwb** [jessepollak/card#155]
See [demo page](http://jessepollak.github.io/card/).

**Comment by jessepollak** [comment]
I'm not seeing  a 404 — can you send a screenshot?

**Comment by talmroth** [comment]
same.  https://cdn.rawgit.com/jessepollak/card/master/lib/css/card.css is returning 404.

**Comment by jessepollak** [comment]
Hm, it's not 404ing for me. Where are you located? Maybe it's caching thing?

**Comment by talmroth** [comment]
US. California. 404 from work, from home, and on cell....

**Comment by kytwb** [comment]
Same, 404 on all devices.
Thailand here.

**Comment by jessepollak** [comment]
Just looked more at this and there `lib/css/card.css` isn't even a thing anymore, so it should be 404ing. I removed the file so the 404 error should be gone. If you're seeing rendering issues, please reopen — that points to something broken with the library.

Thanks for the report!

**Comment by hwdavidward** [comment]
Fyi you still link to the css file from your main page https://jessepollak.github.io/card/ in your "Can I just use the CSS to style cards" section -  https://jsbin.com/cinovupe/3/edit?html,output
