### ISSUE TITLE
Error in rensponsive for mobile

### ISSUE THREAD

**Issue by kiide** [jessepollak/card#158]
In an responsive app, the layout broken

![image](https://cloud.githubusercontent.com/assets/5432753/6317987/b44ba3a2-ba55-11e4-890f-0678c2adf7d2.png)

**Comment by jessepollak** [comment]
Hm, I'm not seeing this as an issue. Can you check your JS console to see if there are any errors?
![screenshot 2015-03-15 16 05 50](https://cloud.githubusercontent.com/assets/1097953/6658642/3f33a432-cb2d-11e4-805e-3d1cb2166070.png)

**Comment by kiide** [comment]
hi, try the cvc field, pelase
