### ISSUE TITLE
Uncaught TypeError: undefined is not a function (at line 1039 in card.js)

### ISSUE THREAD

**Issue by jstol** [jessepollak/card#162]
After creating a new "Card" object, the error `Uncaught TypeError: undefined is not a function` is being raised at line **1039** in card.js.

This is the statement in card.js causing the issue:

```javascript
QJ.append = function(el, toAppend) {
  ...
  return el.insertAdjacentHTML('beforeend', toAppend);
};
```

**Comment by jessepollak** [comment]
What browser are you in?

**Comment by jstol** [comment]
I'm in Chrome. I realized the Card constructor was being called before the document was ready, so the element being referenced didn't exist yet. Might be something good to check against, but this was mostly due to error on my part.

**Comment by jessepollak** [comment]
Mm, thank makes sense. Going to close — thanks for the report anyways!

**Comment by catskul** [comment]
Having the same issue, but calling from inside $(function() {});, so should not be related to @jessepollak  problem.

In any case the demo code in the readme appears to be inoperable as written.

Should I open a separate ticket?

**Comment by catskul** [comment]
Looks like it's just a missing container div. I'll send over a pull request.

**Comment by catskul** [comment]
https://github.com/jessepollak/card/pull/174
