### ISSUE TITLE
There's no way to get card type and restrict allowed card types

### ISSUE THREAD

**Issue by sebrojas14** [jessepollak/card#167]
Some payment systems, like Redeban in Colombia, requires to specify the car type (franchise). For that and for other purposes I think is crucial to have a callback function that receives the selected card type.

I think is crucial also restrict the card types thtat user can use, because some payment systems dins't work with all card types,and some business only wanna receive some types of cards

**Comment by jessepollak** [comment]
Thanks for the feature request, much appreciated!

Card is only a visual tool, not a validation and info gathering tool, so I think these requests are out of the scope for the library. If you want to do them, I'd recommend using [Payment](https://github.com/jessepollak/payment), which is already bundled with card. 

If you disagree with this assessment, reopen the issue with some more thoughts on why this should be included and I'm happy to reconsider. Thanks again for your time!
