### ISSUE TITLE
Please add dinersclub images

### ISSUE THREAD

**Issue by sebrojas14** [jessepollak/card#171]
Hi, dinersclub is detected but is not displayed, what do you need for add dinners club images?

**Comment by jessepollak** [comment]
In order to add Diner's Club, someone needs to add the CSS for the Diner's Club card face. I'm happy to merge a PR with these changes.

I've made a general issue for adding more card faces at #183, so I'm closing this for now. If you'd like to add a PR or have more to share, please comment there!
