### ISSUE TITLE
Allow expiry inputs to work with a select dropdown

### ISSUE THREAD

**Issue by justincron** [jessepollak/card#173]
Is there any way to make this work with a select dropdown for the expiration date? I have a form that I am trying to use this on but their expiration date is two separate select dropdowns (month/year).

**Comment by twohlix** [comment]
:+1: I'm trying to figure this one out too.

**Comment by justincron** [comment]
Thanks @twohlix. You wouldn't think this would be very difficult...the "not so difficult" ones are always the most troublesome :)

**Comment by jessepollak** [comment]
This is something I would really like to see. The basic spec is that right now, expiry fields only work with standard text inputs. I would love to accept a PR that allows the expiry fields to work with an input or a select.

**Comment by avehlies** [comment]
I can take a stab at this.

**Comment by jessepollak** [comment]
Awesome! Don't hesitate to ping me here, [Twitter](https://twitter.com/jessepollak) or email (on my Github profile) if there's any way I can help!

**Comment by kai23** [comment]
Hey,

Any advance on this topic ? (I'm not asking for an ETA)

**Comment by avehlies** [comment]
I've actually not been able to work on this. Between a slew of personal projects and a lack of knowledge of CoffeeScript, I'm going to have to back off of this and let someone else handle it.

**Comment by feliperaul** [comment]
This is really great to improve UX of the form !

**Comment by ammar91** [comment]
Any progress on this issue?

**Comment by huglester** [comment]
Hello,

any updates on this?

**Comment by dmitry** [comment]
Looks like most of the changes should be made in formatter and handler functions.

**Comment by Cloudchoice** [comment]
Someone has achieved some progress in this direction?
It seems one of the most important attributes to be added.

**Comment by fulldecent** [comment]
It appears this question was answered at https://github.com/jessepollak/card/issues/254

If so, please close issue
