### ISSUE TITLE
Ctrl-a does not highlight anything

### ISSUE THREAD

**Issue by doomrobo** [jessepollak/card#175]
Ctrl-a is supposed to do a select-all. It's useful when you've messed up the whole form and you want to start from scratch, you Ctrl-a backspace and try again.

**Comment by jessepollak** [comment]
Thanks for the bug report, much appreciated!

Unfortunately, I'm not able to replicate the issue. In my setup, ctrl-a selection seems to work fine in the inputs. If this is still an issue or I'm misinterpreting the issue, please re-open a longer description.

**Comment by jessepollak** [comment]
Just kidding, I was able to replicate! Tracking the issue in #165.
