### ISSUE TITLE
lib/css/card.css Missing

### ISSUE THREAD

**Issue by zeus3rd** [jessepollak/card#177]
Hi guys,

Good job on this awesome plugin, however it doesn't seem to work out of the box which is really frustrating.

I get the following error:
{URL}/bower_components/card/lib/css/card.css 404 (Not Found)

I'm guessing the css files are built by sass and gulp but my project is using neither. It would be nice to have a generated css file in the repository by default (after all, bower's "main" list expects it anyway)

**Comment by jessepollak** [comment]
There is no CSS file! Can you try updating the version?

**Comment by zeus3rd** [comment]
I have the latest version, and in the latest version your bower file makes reference to "lib/css/card.css"

**Comment by jessepollak** [comment]
Ah, thanks! Fixed :)
