### ISSUE TITLE
Add ability to mask sensitive data

### ISSUE THREAD

**Issue by codenamev** [jessepollak/card#179]
This would be perfect if there was a way to mask the CC number (but for the last 4) after they've entered it.  It is generally bad UX practice to display sensitive data permanently on the screen.  This is in case the info is entered in a public/shared space, you don't want to display sensitive data on the screen.

I'd be happy to help if someone can point me in the right direction

**Comment by erik5388** [comment]
@codenamev,

Please give an example website where CC numbers are masked during input.

This will help identify the priority & need.

**Comment by codenamev** [comment]
https://stripe.com/checkout

**Comment by erik5388** [comment]
![image](https://cloud.githubusercontent.com/assets/183147/8447927/13ca92fa-1f8e-11e5-860b-37e843dbf4cd.png)

@codenamev - wrong. They are not masked.

**Comment by jessepollak** [comment]
No need to be so short - we're all friends here :D

@codenamev I don't think this is a common use case, so I'm not sure it has a use in the library. That said, if you're interested in showing some examples where the UX pattern is used, I'd be happy to consider it!

Thank you both for your time and thought here!

**Comment by codenamev** [comment]
Sorry for the vague response!  The downsides of mobile GitHub ;-)

Masked input is a common UX pattern for "staged" payments (e.g. when confirmation is needed), stored CC info (as referenced in the screenshot from Stripe below), and in cases where screen size is an issue due to keyboard overlays (see [single field payment used by Square's Wallet](http://www.lukew.com/ff/entry.asp?1667)).  Although the later may be outside the scope of masked inputs, it's still justification for it's need I think.

I've seen CC masking (except for the last 4 digits) on many other sites I can't think of off the top of my head; but they're out there.  Mostly useful for staging/storing payment info.

![Stripe's CC masking](https://cloud.githubusercontent.com/assets/109135/8454509/efdc26c2-1fcb-11e5-83ab-7d3004d0164e.png)

**Comment by jessepollak** [comment]
Thanks for the additional information, happy to merge in a PR for this support if someone wants to add it.

**Comment by jessepollak** [comment]
OK, I've opened up a more general issue for this [here](https://github.com/jessepollak/card/issues/184) and I'm confident that it's a feature I'd like to add.

Would really appreciate continued feedback and conversation there — thank you again for your time and thought!

**Comment by erik5388** [comment]
@jessepollak So, I owe @codenamev an apology. I was short. I didn't clearly communicate my intention and perhaps left an unkind feeling amidst.

@codenamev it was a valid feature request and concern. It's fantastic to see it open into a possible future component of yhe software. Keep up the thoughtfulness and creative thinking.

**Comment by jessepollak** [comment]
Aw, thank you for the thoughtfulness, I really appreciate it and I bet @codenamev does as well :D

Thank you both for your contribution to this project!
