### ISSUE TITLE
Version bump for cdnjs

### ISSUE THREAD

**Issue by lukefrake** [jessepollak/card#180]
I wanted to play around with card.js in CodePen, I found [cdnjs had a version](https://cdnjs.com/libraries/card) of card on but unfortunately stopped at version 0.0.2, wondered if we can version bump card.js on cdnjs now the version is 1.0.0?

**Comment by jessepollak** [comment]
I can take a look at this, but it might take a week. We just need to open a PR on CDNJS that adds in the autoupdate from NPM to package.json.

**Comment by lukefrake** [comment]
I actually just used the raw version from Github in the end for my play, but still think this would be worth it :)

**Comment by jessepollak** [comment]
I'm going to close this as I have a PR open with CDNJS.
