### ISSUE TITLE
Compatibilities issues IE8 & IE9

### ISSUE THREAD

**Issue by evansantos** [jessepollak/card#182]
Hello everyone,
I've been using Card inside a project at my work, i had made tests and for me was *working amazingly*!

But until today, when the QA did some regressions tests using **IE 8** and **IE 9**, both didn't workout as expect.

I attached screenshots of both issues, to a better explanation of what happen, i'll explain below:

- IE 8:
	- When I access the page containing card, **only** the form to type the credit card informations appears, as you can see below.
	![fom ie8](https://cloud.githubusercontent.com/assets/1060406/8757246/fa6f9a48-2cae-11e5-8e2e-8939dbdfeba6.JPG)
	
- IE 9:
	- When I access the page containing card, the credit card is loaded but I don't know how it stuck on card back, as you can see below. 	
	![erro ie 9](https://cloud.githubusercontent.com/assets/1060406/8757245/fa55ba42-2cae-11e5-900f-0a2a3f825b00.JPG)
	
If anyone can light up a path to correct it, I'd be so thankful.

**Comment by jessepollak** [comment]
Card only supports IE10+ right now, sorry that's not documented more clearly!
