### ISSUE TITLE
Add missing card faces

### ISSUE THREAD

**Issue by jessepollak** [jessepollak/card#183]
Pretty often, we get a request for a new card. To add a new card, please open a PR with the CSS that recreates that card face.

Here's a list of cards that have been requested: 

* [ ] Diner's Club

**Comment by Fivell** [comment]
FYI https://en.wikipedia.org/wiki/Diners_Club_International#Acquisition_by_Discover_Financial_Services
In 2011, Discover began putting its logo on Diners Club cards. Some payment processors, like PayPal, can only process new Diners Club cards with the Discover logo on them.[citation needed]

So Discover == Diners
