### ISSUE TITLE
Card for React

### ISSUE THREAD

**Issue by shatran** [jessepollak/card#188]
Hi Jesse,

I've wanted to use Card in my project for a long time, but i'm working with React and I couldn't find any good enough React implementations of it. So i built one!  
Of course its heavily based on the original Card code, but I had to really change and add a lot to make it in the React spirit of things. The result is that It has all the features Card has (I think..) including formatting and input validations. 
You can check it out in https://github.com/shatran/card-react

I would love to hear your thoughts and notes about it.

**Comment by jessepollak** [comment]
Awesome! Have you seen [react-credit-card](https://github.com/JohnyDays/react-credit-card)? That's the only other implementation that I've seen around.

**Comment by shatran** [comment]
Yes i saw it, but it's only for displaying the card, and i needed also to format and validate the inputs as well as displaying the card.

**Comment by jessepollak** [comment]
Awesome! I'm going to add a pointer to your library in the docs, is that OK?

**Comment by shatran** [comment]
Yes sure! I'll be glad if you do it.

**Comment by jessepollak** [comment]
Done!
