### ISSUE TITLE
Minor README copy-paste error

### ISSUE THREAD

**Issue by Kwpolska** [jessepollak/card#189]
https://github.com/jessepollak/card/blob/master/README.md#translation

>     // passing in a messages object is another way to
>     // override the default field names
>     messages: {…}

What is the *first* way? This sounds like something copy-pasted from the placeholders section, which uses `placeholders` by default and lists `messages` as its *another way*.

**Comment by jessepollak** [comment]
Ah, this is actually referring to something even older than that! Want to submit a PR for the change? I'm also happy to just do it myself!

**Comment by Kwpolska** [comment]
On Mon, Jul 20, 2015 at 02:33:01PM -0700, Jesse Pollak wrote:
> Ah, this is actually referring to something even older than that! Want to submit a PR for the change? I'm also happy to just do it myself!

Please do it yourself I’m not sure what it should say, exactly.

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16

**Comment by jessepollak** [comment]
Thanks!
