### ISSUE TITLE
Predictive text in Android interferes with this widget

### ISSUE THREAD

**Issue by manioube** [jessepollak/card#196]
When predictive text is activated in Android, it seems **formatCardNumber**, **formatCardExpiry** and **formatCardCVC** are not called, or not working properly.
It happens both with *card.js* and *card.jquery.js*

Customers would be unable to proceed with the purchase: expiry date cannot be entered properly. The slash, which should be added automatically, does not appear. And it cannot be added by hand, apparently. Odd.

Other than that: fantastic tool :)

Hope someone has a hint on how to fix this, or a workaround, as I'm rather unfamiliar with Android specifics.

**Comment by jessepollak** [comment]
I'm going to close this in favor of #199. If you think they are two separate issues, please reopen!
