### ISSUE TITLE
getting this error 'Uncaught TypeError: el.insertAdjacentHTML is not a function'

### ISSUE THREAD

**Issue by ammark47** [jessepollak/card#198]
I keep getting this error and also I can't find the css and where I just get a grey card that doesn't have respond to input.

**Comment by AndrewDryga** [comment]
Is seems that you forgot to set container option:
```
container: '.addcard__previev', // *required*
```

See docs.

**Comment by lrodriguezrullan** [comment]
I am also getting the same issue. I did set the container option. I tried also with the Angular version and am getting the same issue.

**Comment by joryhatton** [comment]
+ 1 on this.  seems persistent no matter any change.

**Comment by 3dd13** [comment]
perhaps the container was not there when you new the Card ?
try check by running this before new Card(options)

    console.log(document.querySelectorAll('#container-id'));

Angular version even more possible that you put the directive in some templates that are not visible or attached to DOM yet ?

**Comment by hgoldwire** [comment]
Second 3dd13.  When I use these in angular2, I can't create a Card in the constructor bc the dom isn't set up yet.  Doing it in ngOnInit works--presumably angular1 has similar lifecycle.

**Comment by jessepollak** [comment]
It looks like this issue is resolved — if y'all are still having issues, please reopen!
