### ISSUE TITLE
Card brand "elo" no detected

### ISSUE THREAD

**Issue by reginaldojunior** [jessepollak/card#200]
The card of brand "elo" no is detected. 

Examples of numbers this card find in https://gist.github.com/erikhenrique/5931368

**Comment by darlanmendonca** [comment]
Some intend to add support for brand "elo"?

**Comment by Fivell** [comment]
this can help to add support for ELO brand
https://github.com/Fivell/credit_card_validations/commit/7ee9a809c5682760a363a334109846e3d5a0c37a

**Comment by evansantos** [comment]
@darlanmendonca @reginaldojunior i think that would be nice if you could implement this, @jessepollak would be glad =D

**Comment by darlanmendonca** [comment]
right, I will make a pull request following logic and structure of @jessepollak with:

- regex to idetify elo cards
- draw of brand in css only

**Comment by reginaldojunior** [comment]
:+1: 

When possible create a pull request'm kind of out of time now.

**Comment by evansantos** [comment]
GREAT, SCOTT!!! 

@darlanmendonca you had to modify this little buddy here https://github.com/jessepollak/payment/blob/master/src/payment.coffee

**Comment by reginaldojunior** [comment]
Guys i am try add this brand, but I don't know where in files scss to compile automatic.

**Comment by reginaldojunior** [comment]
Done! 

:smile:

**Comment by evansantos** [comment]
awesome @reginaldojunior... did you added your regex to [payment.coffee](https://github.com/jessepollak/payment/blob/master/src/payment.coffee)?

**Comment by reginaldojunior** [comment]
The units tests did stay wrong I am try to fix. :bug:

**Comment by jessepollak** [comment]
Will be fixed in v1.2.0!
