### ISSUE TITLE
Support number inputs for a better mobile experience

### ISSUE THREAD

**Issue by scottmboring** [jessepollak/card#207]
Only 'text' inputs work which brings up the wrong keyboard on mobile devices for numeric fields. Being able to set the input type to 'number' will improve the mobile experience.

**Comment by poacher2k** [comment]
Have you tried using `inputmode="numeric"` for this? [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-inputmode)

**Comment by scottmboring** [comment]
I was not aware of that option; however, I started using type='tel' which works well especially since decimal points are needed.

**Comment by KrunchMuffin** [comment]
nobody supports inputmode
http://www.wufoo.com/html5/attributes/23-inputmode.html

**Comment by jessepollak** [comment]
Thanks for the solution @scottmboring! I'm closing this since using type='tel' is supported.
