### ISSUE TITLE
Can we safely use provided validation?

### ISSUE THREAD

**Issue by juliomac** [jessepollak/card#208]
I understand from your answer to https://github.com/jessepollak/card/issues/144 that validation is not the intended purpose of Card.

However, we can find some pretty good validation already in it (possibly coming from Stripe query payment?).

I've been playing with the following and found it pretty nice:

    Payment.fns.cardExpiryVal();
    Payment.fns.validateCardExpiry(objVal.month, objVal.year);
    Payment.fns.validateCardNumber(val);
    Payment.fns.cardType(val);
    Payment.fns.validateCardCVC(val, _this.cardType);

Rather than adding yet another library (jquery.payment), how far can I go using just what is already available? What I would be missing?

In case I use payment library, would that cause any Namespace issues?

**Comment by jessepollak** [comment]
@juliomac that's actually [payment](https://github.com/jessepollak/payment), which is meant to have parity with `jquery.payment`, but without `jQuery`. Definitely use it!
