### ISSUE TITLE
Firefox background error

### ISSUE THREAD

**Issue by workgena** [jessepollak/card#212]
![screen shot 2015-11-26 at 17 59 55](https://cloud.githubusercontent.com/assets/9843321/11426877/be8e7dca-9467-11e5-9d44-bcd0a605e990.png)
In latest Firefox **Mac OS X** I caught this error. It not always appears. To reproduce it you will need to:

1. Refresh page
4. Type "41111111"

If image is normal, then repeat this two steps. Error not always appears.

I've resolve it by replacing this part of code:

```
.jp-card.jp-card-identified .jp-card-front, .jp-card.jp-card-identified .jp-card-back {       background-color: #000;       background-color: rgba(0, 0, 0, 0.5); }
```
with
```
.jp-card.jp-card-identified .jp-card-back {       background-color: #000;       background-color: rgba(0, 0, 0, 0.5); }
```
Also I don't understand why there are two "background-color" ?

**Comment by omeraplak** [comment]
+1

**Comment by barinali** [comment]
+1

By the way, @workgena there are two background-color for rgba() fallback; Some browsers don't support rgba() and fallback the previous background-color definition.

**Comment by workgena** [comment]
@barinali thx, now I understand.

**Comment by jessepollak** [comment]
Hi, I'm not able to reproduce this issue. If you're still experiencing it, can you reopen this issue with a bit more information on reproduction? Thanks!
