### ISSUE TITLE
QJ inclusion issue

### ISSUE THREAD

**Issue by Yottster** [jessepollak/card#214]
Perhaps this is obvious and not an issue, but currently QJ gets included 3 times in the built files.
Is it possible to avoid this, somehow?

See:
https://github.com/jessepollak/card/blob/c2341acb951f9f57518ee734d4d2d761deff2ba9/lib/js/card.js#L857
https://github.com/jessepollak/card/blob/c2341acb951f9f57518ee734d4d2d761deff2ba9/lib/js/card.js#L1461
https://github.com/jessepollak/card/blob/c2341acb951f9f57518ee734d4d2d761deff2ba9/lib/js/card.js#L2289

**Comment by jessepollak** [comment]
Thanks for the report!

**Comment by jessepollak** [comment]
Fixed in `v1.2.1`!

**Comment by Yottster** [comment]
Super! Thanks!
