### ISSUE TITLE
Card Options

### ISSUE THREAD

**Issue by saccccchin** [jessepollak/card#215]
Is it possible to reset the card to original ( grey background ) by using javascript function rather than keyup event.

**Comment by MouseEatsCat** [comment]
The div with the class "jp-card" is what's controlling the background color (css). So if you want to make the card reset to the "unknown" state, you can create a Javascript function to change the class of the div to "jp-card jp-card-unknown".

For example with jQuery you can do:
`$(".jp-card").attr("class", "jp-card jp-card-unknown");`

**Comment by saccccchin** [comment]
Thanks mate!!!
Well I did figure that changing class to jp-card-unknown gets backs to grey background. 
I was in general asking for reset function which shall set background to grey color and set credit card number , expiry date and cvc number to ***.

**Comment by jessepollak** [comment]
The library currently doesn't provide this option and I think it will remain that way. I generally view Card as a view layer, which mirrors the form — adding logic to manipulate the form to card seems counter to that view.

If you have a compelling case for why this should be added, I'd be open to discussing and merging a PR.

Thanks for your thought and time!
