### ISSUE TITLE
form complete callback

### ISSUE THREAD

**Issue by jersingh** [jessepollak/card#216]
This is a great library and I don't want to sound ungrateful, but does this library support callbacks when all form fields are properly filled in?

Button submission button easily enabled/disabled then.

Thanks

**Comment by TrevorHinesley** [comment]
Why don't you just write a small function to check that all fields are filed in? Whatever credit card processing system you're using should check validity of the field values upon submission, so all you should need to do is make sure the necessary fields are at least filled out, in the format you need.

**Comment by jessepollak** [comment]
Thanks for the issue open, I appreciate it! For now, card is a view-layer library, so I don't want to add any more logic like this to the library. That said, you should be able to use [Payment](github.com/jessepollak/payment) to accomplish this pretty easily.
