### ISSUE TITLE
how to build a version without sourcemap?

### ISSUE THREAD

**Issue by chenjau** [jessepollak/card#220]
here is the stupid question, how to build a version without sourcemap for production use? 
after googled for gulp,  browserify, vinyl-source-stream for hours, hacked gulpfile, I give up.
please help, thanks.

**Comment by jessepollak** [comment]
Hm, the standard build doesn't include a sourcemap, so I'm not quite sure what you're referring to. If you're building with a different gulpfile or browserify setup, you should ensure that `debug` is not equal to `true`. You can see how that's accomplished in this project [here](https://github.com/jessepollak/card/blob/master/gulpfile.coffee#L28).

**Comment by jessepollak** [comment]
May have spoken too soon: seems like the CSS sourcemaps are being included. Looking into this!

**Comment by jessepollak** [comment]
Fixed in `v1.2.1`!
