### ISSUE TITLE
Card width doesn't work in cordova app

### ISSUE THREAD

**Issue by jtmarmon** [jessepollak/card#221]
I'm using ionic for a cordova app. No matter what CSS/HTML configuration I try, I can't seem to change the card width using the `width` parameter..

`<div class='card-wrapper'></div>`
```js
// card_controller.js
var card = new Card({
  form: 'form',
  container: '.card-wrapper',
  width: 200,
  placeholders: {
    number: '**** **** **** ****',
    name: 'john doe',
    expiry: '**/****',
    cvc: '***'
  },
  formSelectors: {
    nameInput: 'input[name="first-name"], input[name="last-name"]'
  }
});
```

**Comment by jtmarmon** [comment]
Happy to provide more info if needed. Not sure what's relevant in a cordova-related bug report

**Comment by jessepollak** [comment]
Hi, I'm closing this issue because it's been open with no response. Can you please reopen with a more information if you're still having this problem?

Thanks!
