### ISSUE TITLE
Card renders 7 times, but not all the time

### ISSUE THREAD

**Issue by brandoc0mmand0** [jessepollak/card#227]
When the page loads, the Card UI gets rendered 7 times. If I click out to a new page and load a new php session, the card UI works properly.

Also - When turning debug: true, I get failures saying card cannot find the input fields, although filling ou the form fields populates the UI.

![screen shot 2016-01-21 at 3 20 19 pm 3](https://cloud.githubusercontent.com/assets/2006553/12497804/e57d1bdc-c052-11e5-9ee9-76ab16d00668.png)

**Comment by Jmdavison** [comment]
I am having this issue as well, my card renders twice, but when the session is cleared, it returns to one. Not sure what is causing this, 

_Thanks_

**Comment by brandoc0mmand0** [comment]
Couldn't come up with a fix for this. Ended up hiding the other instances via javascript.

**Comment by jessepollak** [comment]
Could the JS file be loaded multiple times?

**Comment by Jmdavison** [comment]
I don't believe it is, what is interesting, though, is that one card is loaded with the default width, while the other is loaded at the width I specified in my call. And that the one with the specified width is the only one that reacts to the form elements.

**Comment by brandoc0mmand0** [comment]
Same here, only being loaded once.

**Comment by Jmdavison** [comment]
_Update_:

I've found that the card only renders twice when I am logged into my wordpress admin, I assume that Jesse was right and this is causing the script to be loaded again somewhere, will continue to dig.

Thanks

**Comment by Jmdavison** [comment]
_update_:

I figured it out, the jQuery selector I used to find my form, was hitting multiple forms (such as the one created by the admin panel in WordPress) but was putting the extra render into the container specified.

So I changed my selector from `$('form').card()` to  `$('#id_of_form').card()` and it was fixed!

**Comment by jessepollak** [comment]
Great, I'm closing this issue. Please reopen if you're still having problems.
