### ISSUE TITLE
Remove jQuery dependence and offer a jQuery plugin in addition to normal library

### ISSUE THREAD

**Issue by MoOx** [jessepollak/card#23]
I'm not sure this nice lib really require jquery.
It seems a good option to make something jquery free, then make available a jquery plugin (eg: [Pikaday](https://github.com/dbushell/Pikaday) do that).

**Comment by jessepollak** [comment]
Just shipped `v1.0.0-beta` which removes the jQuery dependence. Check it out [here](https://github.com/jessepollak/card/releases/tag/v1.0.0-beta).

Would love to see people using and giving feedback on it!

**Comment by jessepollak** [comment]
This is going to ship in v1.0.0 later today! WOOOOO!

**Comment by jaypalkadam** [comment]
Hey hi sir this your great work.
Thank's for it 

i have one problem with it . i have to use only backside .

Can you help me?

**Comment by uetkaje** [comment]
Jquery still dependency according to bower.json. Please update bower.json file.
