### ISSUE TITLE
Magento implementation

### ISSUE THREAD

**Issue by tufanayd** [jessepollak/card#236]
Hi,

I am trying to implement this however I am getting the below error:

prototype.js:828 Uncaught TypeError: Payment.formatCardNumber is not a function

**Comment by jessepollak** [comment]
Hi, I'm closing this issue as it's been open for a while with no response. Can you reopen if you're still having this problem? Thanks!

**Comment by Stasevi4** [comment]
Hi i have same problem. Magento comes with Payment object

**Comment by murilohns** [comment]
Hello @Stasevi4 and @tufanayd, did you solved this problem? Can help me with it?
