### ISSUE TITLE
Add new cards

### ISSUE THREAD

**Issue by jvcunha** [jessepollak/card#238]
Hi,
    I need other cards that are not available today. Are they:
    - Aura
    - Cabal
    - Hiper
    - Hipercard
    - VerdeCard
    - Verocheque
    and others...

    How to put images and validate the BIN of each?

**Comment by jessepollak** [comment]
Hi, if you'd like to add more cards, please submit a PR with the necessary CSS and CoffeeScript to implement them. You can find a guide for contributing [here](https://github.com/jessepollak/card/blob/master/CONTRIBUTING.md).

**Comment by jvcunha** [comment]
Jesse,
    I would love to work but did not understand the code yet. Sorry, javascript and css are not my strong. I did not understand yet where the css is informed logo (image) of each flag.
I can not help it.
