### ISSUE TITLE
Add an option to disable validation for inputs

### ISSUE THREAD

**Issue by dcardosods** [jessepollak/card#239]
In a project, I'm using Card along with a Stripe lib which already validate the inputs for me. Having two validations is causing conflicts. Maybe more people have the same problem.

Would it make sense to have an option to not validate the inputs? In which case whatever the user enters as input will be shown in the card container.

**Comment by jessepollak** [comment]
I'm open to this as a feature — if you'd like to submit a PR, I'd be happy to help in any way I can!

**Comment by fulldecent** [comment]
Recommending to close this issue for lack of interested implementers
