### ISSUE TITLE
Cards in modal

### ISSUE THREAD

**Issue by jvcunha** [jessepollak/card#240]
I put the cards in a modal.
When I open the modal already inform the values of each input but the image does not update.
How do I do that ?
Thanks

**Comment by jessepollak** [comment]
Hi, thanks for opening an issue! Unfortunately, I can't quite understand the problem you're having. If you're still struggling with this, please reopen the issue with more information.

Thanks!

**Comment by jvcunha** [comment]
Jesse,
   resolved with Issue #184
