### ISSUE TITLE
card container overflows onto for on small screens

### ISSUE THREAD

**Issue by cdaringe** [jessepollak/card#243]
when viewing on small device, e.g. iphone 4, the card overflows into the form field.  easily reproducible with iOS simulator or real iphone!

<img width="432" alt="screen shot 2016-04-16 at 2 11 29 pm" src="https://cloud.githubusercontent.com/assets/1003261/14583366/30a03324-03dd-11e6-9942-71d506123edd.png">

**Comment by jessepollak** [comment]
Hi! You should be able to fix this using the `width` option or using a CSS selector to scale the container. Thanks!

**Comment by cdaringe** [comment]
hi @jessepollak!  thanks, sorry for the delayed response.  the card expanded outside of it's container element in this case.  is there anything requiring setting to make it fully self-contained/responsive?  perhaps from your point of view it is supposed to, it's just not what i experienced.  i did try and remove our own CSS to isolate it from our content.  again, it was _only_ on iOS devices--it did scale per expectation on other devices!  thanks again!

**Comment by hounw** [comment]
@cdaringe where you able to fix this?

**Comment by cdaringe** [comment]
Sorry, I have long detached from that project to no longer have access to
the source code. Unfortunately I cannot recall
