### ISSUE TITLE
Card formatting not working on Chrome android

### ISSUE THREAD

**Issue by dcardosods** [jessepollak/card#249]
Test case: http://embed.plnkr.co/0lnlUxeSy2en3m5xaE8u/

Tested on Chrome 50.0.2662.89, Android 5.1

**Comment by rylwin** [comment]
I'm seeing the same thing, same versions:  Chrome 50.0.2662.89, Android 5.1.0.

What's odd is we had a server-side issue come up as a result of unexpected formatting of the expiration date field. When I tried on my mobile device (~ 1 month ago) when this happened. I couldn't replicate it, but today (perhaps after a Chrome for Android update?) I'm having this issue on my device.

**Comment by rylwin** [comment]
I think this is a duplicate of https://github.com/jessepollak/card/issues/199

**Comment by jessepollak** [comment]
This is a duplicate of #199. Thanks for reporting!
