### ISSUE TITLE
Implement name length checks and year validation

### ISSUE THREAD

**Issue by JamesDonnelly** [jessepollak/card#25]
![image](https://cloud.githubusercontent.com/assets/2203377/3188308/8a008e24-ecb9-11e3-9e90-554473578a4e.png)

The Name field doesn't appear to have any length checks. The MM/YY field accepts 13 to 19 as a valid month, and up to 9999 as a valid year. It also accepts years less than the current year.

**Comment by jessepollak** [comment]
I'm going to close this issue as it has been stale for a while and generally falls outside of the primarily visual scope of Card. 

Thanks for all of the feedback!
