### ISSUE TITLE
Diners support

### ISSUE THREAD

**Issue by avifatal** [jessepollak/card#253]
Hi,
I see that this lib has no support in Diners (http://www.stevemorse.org/ssn/List_of_Bank_Identification_Numbers.html).

What can be done about it?
Can I intercept and add it myself?

Thannks

**Comment by avifatal** [comment]
Anyone can suggest how to resolve this issue?

**Comment by Yottster** [comment]
See this issue & comment: https://github.com/jessepollak/card/issues/183#issuecomment-154502921
