### ISSUE TITLE
Expiry month and year with two input fields

### ISSUE THREAD

**Issue by ivanstojkovicapps** [jessepollak/card#254]
Hi,

is it possible to have two input fields for expiry? One for month and one for year?

best regards Ivan

**Comment by zchristopoulos** [comment]
In addition, if you could also explain if it's possible to utilize select inputs for this?

**Comment by Yottster** [comment]
Two inputs for expiry:
```
formSelectors: {
    expiryInput: ['input[name="cardexpires[month]"]', 'input[name="cardexpires[year]"]']
}
```

@zchristopoulos  see https://github.com/jessepollak/card/issues/173

**Comment by jessepollak** [comment]
Thanks @Yottster!
