### ISSUE TITLE
Formatting and Angular JS

### ISSUE THREAD

**Issue by ivanstojkovicapps** [jessepollak/card#255]
Hi,

when formatting is turned on and ng-model is set on input field, the value for model is set until the formatting takes effect (until the space is put in).
For example:
when input is set to 424 the model is set to 424
if i insert 4242 the formatting transforms the value in input to "4242 " but the model remains 424
when i insert 42424 the input is transformed to "4242 4" and the model is set right.

Is this a known issue?

best regards Ivan

**Comment by ThadeuLuz** [comment]
+1

**Comment by ThadeuLuz** [comment]
As a workaround, using vanilla js works.

`document.querySelector("input[name=ccnumber]").value`

**Comment by ThadeuLuz** [comment]
This happens because validation changes the input value directly, not triggering angular's input event.

to fix this you can add one line to the source code:

    QJ.val = function(el, val) {
      var ret;
      if (arguments.length > 1) {
        el.value = val;                              // <== Remove "return" from this line
        return angular.element(el).triggerHandler('input'); // <== Add this line!
      } else {
        ret = el.value;
        if (typeof ret === "string") {
          return ret.replace(rreturn, "");
        } else {
          if (ret === null) {
            return "";
          } else {
            return ret;
          }
        }
      }
    };

**Comment by thierryler** [comment]
I do have the same problem with Meteor/ReactJs

**Comment by brunosoaresds** [comment]
I'm dispatching the events manually, so the input is reformatted. After change the ngModel data, do it:

```
let dispatchEvents = ['keypress', 'keydown', 'keyup', 'paste'];
    dispatchEvents.forEach(event => {
      this.card.$numberInput[0].dispatchEvent(new KeyboardEvent(event));
      // ... Dispatch in some other inputs...
    });
```

**Comment by melloware** [comment]
There is now an Angular wrapper for Card: https://github.com/ihym/ngx-card
