### ISSUE TITLE
Multiple fields not passing values during a $POST

### ISSUE THREAD

**Issue by lemusi** [jessepollak/card#256]
Hi,
I don't know if I am doing something wrong, but when I try using multiple fields (first-name, last-name) the values don't get passed through the $POST method in the form.  It works when I use the singular (name) field.  But I need it separated.
form action="http://somepage" method = "post" 
input placeholder="Enter First Name" type="text" name="first-name"/
I am using the suggested form selectors in the java script:
formSelectors: {
        nameInput: 'input[name="first-name"], input[name="last-name"]'
    }

Thanks for your help!

**Comment by lemusi** [comment]
2 days and no response? Thanks any way...

**Comment by calebh05** [comment]
This is related to [https://github.com/jessepollak/card/issues/254](254) I think, same problem different fields.

**Comment by jessepollak** [comment]
I don't think those two issues are related. This seems like an issue with your form rather than card, so unfortunately I can't help out here. Good luck!
