### ISSUE TITLE
Stripe Compatibility

### ISSUE THREAD

**Issue by pradt** [jessepollak/card#261]
This would be great to use it along side Stripe. However, the input tags contain the name attributes - which I believe against Stripe (due to PCI DSS standard). 

It would be great, if this can be completed for stripe and non-stripe.

**Comment by matthewarkin** [comment]
the input tags having a name attribute are only against PCI dss if you wrap the inputs in a form such that when you submit the form the inputs are also posted.

**Comment by tgdn** [comment]
You can simply provide a `formSelectors` object with the different selectors for each element:

    const card = new Card({

        container: '.card-wrapper',

        formSelectors: {
            numberInput: 'input#number',
            expiryInput: 'input#expiry',
            cvcInput: 'input#cvc',
            nameInput: 'input#name'
        },
    })

which then allows you to use what is documented by Stripe and be PCI DSS compliant:

    <input data-stripe="number" id="number" />
    <input data-stripe="expiry" id="expiry" />
    <input data-stripe="cvc" id="cvc" />
    <input data-stripe="name" id="name" />

**Comment by kaosengr** [comment]
I don't understand the original poster's issue.  

Data has to be POST'd to Stripe with the identifier they expect.  

Can anyone give more details as to the PCI DSS compliance problem?

**Comment by matthewarkin** [comment]
@kaosengr the data is not posted to Stripe via a form post, its done via ajax / javascript, thus no need for `name` attributes. In order to ensure that no card data is posted to the merchant's server, its common to ensure that the card inputs do not have a `name` attribute since only those attributes get posted to the server.

**Comment by kaosengr** [comment]
So, even though a form is passed to a client's browser and the action URI is to a remote server, data gets passed back to the webserver from whence the page came?  I thought the browser processed the form and passed data only to the action URI's server.

**Comment by matthewarkin** [comment]
The standard stripe form would like like this:

```
<form action="charge.php">
<input type="number" id="ccnum">
<button type="submit">
</form

<script>
$(form).onSubmit(function(e){
    stripe.createToken(form, function(token){
        form.append(token);
        form.submit();
    }
})
</script>

```
so the card number gets sent to stripe, and the form minus card data to the merchant's server

**Comment by kaosengr** [comment]
If setting up a direct payment form on the merchant's e-commerce server and your site is not PCI DSS approved, it should not have the card number sent via a 'name' form input back to the server for processing. I'm starting to see now, the darkness is fading.

**Comment by DVermette018** [comment]
@matthewwarkin
Actually, stripe standard is using stripe.js to provide a token with data entered on client-side. Then this token only is sent to stripe.
So the card number, and all other data entered in the form is only appearing on client-side and should never be sent elsewhere for security reasons. It is better not to add a 'name' input just for your customers' security, but for as much as I know, Stripe does allow it.

**Comment by jessepollak** [comment]
Hi, this has already been discussed in #233 - closing this as well!
