### ISSUE TITLE
Validate the form fileds on the click of submit button

### ISSUE THREAD

**Issue by usamamashkoor** [jessepollak/card#264]
Hi 
Currently the validation is working fine on input.
but the form is being submitted if we click on the form submit button.
is their a way we can also restrict the user from submitting the form if the validation is not true.

Here is my js code

    var card = new Card({
          	    		    form: document.getElementById('formCreditCard'),
    		    	    container: '.card-wrapper',
          		    	    formSelectors: {
		      	                numberInput: 'input#numberCCard', // optional — default input[name="number"]
       			            expiryInput: 'input#expiryCCard', // optional — default input[name="expiry"]
	      		            cvcInput: 'input#cvcCCard', // optional — default input[name="cvc"]
		    	            nameInput: 'input#nameCCard' // optional - defaults input[name="name"]
			       },
			    placeholders: {
			        number: '**** **** **** ****',
			        name: 'Arya Stark',
			        expiry: '**/****',
			        cvc: '***'
			    }
			});
Thanks and Regards
M.Usama

**Comment by jessepollak** [comment]
Hi! This validation check is outside of the scope of card, which focuses entirely on displaying rather than validating. You can use the included [payment](https://github.com/jessepollak/payment) to do additional validation.
