### ISSUE TITLE
Impossible to use card without some build system like webpack/browserify/systemjs

### ISSUE THREAD

**Issue by le0pard** [jessepollak/card#265]
Hello. Looks like after release version 2.0 right now is impossible to use card.js just in browser without build system like webpack/browserify/systemjs. Is this how it expected from new release?
![card](https://cloud.githubusercontent.com/assets/98444/17135509/cc05c4be-5338-11e6-8608-16e371ea616d.png)

**Comment by jessepollak** [comment]
As the README mentions, you need to use the [dist/card.js](https://github.com/jessepollak/card/blob/master/dist/card.js) file.

**Comment by jessepollak** [comment]
You can see an example of this usage on the [demo page](http://jessepollak.github.io/card/) right [here](https://github.com/jessepollak/card/blob/gh-pages/index.html#L142).

**Comment by le0pard** [comment]
I use https://rails-assets.org/#/components/card, which use bower package for build. And looks like after some changes (maybe in bower.json) now it contain coffee scripts:

![card](https://cloud.githubusercontent.com/assets/98444/17146552/99c9c7dc-5367-11e6-8dd0-93ed3115e619.png)

**Comment by jessepollak** [comment]
Ah, interesting — I just published a [new release](https://github.com/jessepollak/card/releases/tag/v2.0.2) can you try installing that? Thanks!

**Comment by le0pard** [comment]
Looks like all works. Big thanks, @jessepollak !

**Comment by jessepollak** [comment]
Thanks for catching that!
