### ISSUE TITLE
ELO, any 16 digit number ending in 5067 

### ISSUE THREAD

**Issue by dhobdensa** [jessepollak/card#268]
We had a customer using a visa card ending in 5067, the plugin believes this to be 'elo' instead of 'visa'. We only accept visa and mastercard so this required quite a quick hotfix where we had to disable validation temporarily.

The pattern I can figure out so far is any 16 digit number that does not start with 5, and also ends in 5067

*Update*
It seems that the sequence 5067 does not have to be at the end, it can occur anywhere in the number

**Comment by jessepollak** [comment]
Thanks for the report - will be fixed upstream in payment `v2.1.3`!
