### ISSUE TITLE
Does not work with iOS4 and Android4

### ISSUE THREAD

**Issue by MimRaCreative** [jessepollak/card#269]
Does not leave space when writing the card number and the card size is not changed. See pls for example https://www.camasirpijama.com/ 
Could you pls help me...

**Comment by Iftahh** [comment]
For me (testing in Android Chrome) - I found everything works **if** I change the input type of number/expiry/cvc  to "tel" -

this also sets a proper digits keyboard and has the neat side affect of fixing the `keypress` and `e.which` events.

Would love to hear if it fixes on other devices/browsers as well.

**Comment by jessepollak** [comment]
@jacobcarrington from your digging, do you think there is a chance we should make in the library to help resolve this? Thanks!

**Comment by jessepollak** [comment]
I believe this is also a duplicate of #199. Closing in favor of that one.
