### ISSUE TITLE
Formatting Visa makes problems with React

### ISSUE THREAD

**Issue by thierryler** [jessepollak/card#273]
Hello

I do have problem when using the lib with React.js, with formatting enabled and Visa.

To explain : On my input, I added a method that writes the typed value 

```
onNumberChange = value => {
  console.log('New number :', value);
  this.number = value;
  ...

<Input
  name="number"
  label="Numero"
  value={this.number}
  onChange={this.onNumberChange}
}
```

If I type 4000 1234 1234 1234 (visa card), it logs 4000 1234 1234 123. The last digit is missing. But if I type 1234 1234 1234 1234 (invalid number), it logs the 16 digits...

On the visual card, all is ok, but not in memory...

**Comment by kencana-voilaah** [comment]
hey there, encountered the same thing, for the temp fix, I applied onBlur event to that particular Input element and grab the final value

**Comment by jessepollak** [comment]
Hi! Is this only happening when used in React? Are you writing your own wrapper or are you using an upstream library that uses Card? Thanks!

**Comment by thierryler** [comment]
Hello, I use card only.

**Comment by jakebian** [comment]
@thierryler did you find a solution to this?

**Comment by jakebian** [comment]
Looks like on the last digit type the input field changed without firing the changed event (maybe a preventDefault somewhere), a hacky solution, as noted earlier by @kencana-voilaah, is to listen for the onBlur event, but ultimately @jessepollak this looks like a bug.

**Comment by thierryler** [comment]
Well no solution. I had to stop to use it. Instead I use https://github.com/JohnyDays/react-credit-card. It is really not as good as card but it works. And I wrote a lot a code to add missing functionnalities.
