### ISSUE TITLE
Back of card issue

### ISSUE THREAD

**Issue by amcgee7** [jessepollak/card#279]
I have found an issues with your demo page.  I'm using google chrome so that might be important.  I click the cvc field and the card does flip but soon after all the other information appears but backwards.  I'm unsure why.

**Comment by TommyChanthaboune** [comment]
@amcgee7 See #276

**Comment by sritampatnaik** [comment]
I am getting this issue as well

**Comment by jessepollak** [comment]
Fixed in #285, shipping as `v2.0.4`. Thanks y'all!
