### ISSUE TITLE
Compiled CSS oddities

### ISSUE THREAD

**Issue by Smashman** [jessepollak/card#28]
See: https://github.com/jessepollak/card/blob/master/lib/css/card.css#L407

This line has one linear-gradient with a `-webkit-` prefix despite the rest not having the prefix.

Also I have no idea why the `background-image`s are repeated twice each. The single difference is in the sheen on the top left. The top one has a degree of 245 and the other has -115, functionally identical in every way.

I'm not used to scss, so I couldn't find the issue at hand.

**Comment by jessepollak** [comment]
Thanks for all the feedback here.

I'm closing as this has been stale for a long time and we switched CSS compilers a while ago. Please reopen if it's still an issue for you!

**Comment by Smashman** [comment]
Looks like you didn't have the energy!

**Comment by jessepollak** [comment]
:)

**Comment by Yottster** [comment]
We have been noticing this issue as well. Seems as though bourbon currently doesn't have support for prefixing of any repeating gradient. Quite easy to add support to the newest bourbon version though.
