### ISSUE TITLE
Development build fails on Windows

### ISSUE THREAD

**Issue by LoveSpirals** [jessepollak/card#289]
I followed the instructions to build card.js locally on my Server 2012 R2 box, and I receive the error below. I used a bash command prompt.

I also tried setting NODE_ENV as so:
-          NODE_ENV=”production npm run compile”
-          export NODE_ENV=”production npm run compile”

I also have latest npm and node installed.
Any ideas?

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":
"win32","arch":"x64"})
npm WARN card@2.0.3 No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! card@2.0.3 prepublish: `NODE_ENV=production npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the card@2.0.3 prepublish script 'NODE_ENV=production npm run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the card package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs card
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls card
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\Git Projects\card\npm-debug.log

**Comment by jessepollak** [comment]
Fixed in 2.0.5.
