### ISSUE TITLE
Card should handle `value` values correctly in initial rendering

### ISSUE THREAD

**Issue by thedavidscherer** [jessepollak/card#29]
When the form is partially pre-filled with address data, it should display this on the card.

I can't figure out how to get it take the pre-fill data and use it, tabbing around the form causes the image to update, but triggering clicks, focus, change, etc does not. Also, it only updates the image with pre-fill data from a field you tab into focus, not tabbing out (blur).

What's the easiest way to update the image with data place in the form from the DB?

**Comment by verdugokali** [comment]
the answer isn't that clear. I have same problem. Help me please
