### ISSUE TITLE
How to change card number format?

### ISSUE THREAD

**Issue by obzc** [jessepollak/card#292]
Hi,

I need no spaces card number.

My card number format: XXXXXXXXXXXXXXXX

**Comment by BallisticPain** [comment]
I ended up stripping them out on my server side. However, this would be useful to get just the number without the formatting.

Here's what is recommended on StackOverflow: http://stackoverflow.com/a/5963202/5399323

**Comment by jessepollak** [comment]
@BallisticPain — thanks for all of your helpful comments here and throughout the repo! I just added you as a contributor, if you're interested in continuing to help me maintain and document the library :)

**Comment by BallisticPain** [comment]
@jessepollak Thanks! I have accepted... you have a great thing going, and I appreciate the invitation to help!

**Comment by BallisticPain** [comment]
@obzc 
Do you have the availability to create a PR that removes the spaces?

**Comment by sanket044** [comment]
Just use 

formatting: false
