### ISSUE TITLE
Structure/Breakup Documentation

### ISSUE THREAD

**Issue by BallisticPain** [jessepollak/card#296]
I believe this could use a bit more documentation structure.

Readme to showcase the library, mention those who are using the library, maybe mention contributors. The Readme would also link to the rest of the documentation.

1. Installation Instructions (NPM, Bower, GitHub)
2. Usage
3. Example(s)
4. API (I think the jQuery is mostly lacking the API ability currently)

**Comment by BallisticPain** [comment]
Another issue that could be better documented: #326

**Comment by fulldecent** [comment]
Recommending to close this issue for lack of initiative
