### ISSUE TITLE
Back of card no longer shown in IE11

### ISSUE THREAD

**Issue by mlev** [jessepollak/card#297]
The back of the card is no longer shown in IE11. You can recreate this on the demo page (https://jessepollak.github.io/card/).

This seems like a regression from the last release - if I force backface-visibility=visible then it is shown.

**Comment by BallisticPain** [comment]
This is likely from this change: https://github.com/jessepollak/card/blob/master/src/scss/card.scss#L45

@mlev Could you confirm that IE11 has the .js-card-flipped class on the container when this happens?

It seems we may need to have some logic around IE vs Chrome on this behavior.

**Comment by mlev** [comment]
Yeah - it has that class (see screenshot). If I toggle off the backface-visibility style in the dev tools then the back of the card is shown.

![virtualbox_ie11 - win7_22_11_2016_08_42_18](https://cloud.githubusercontent.com/assets/3466386/20501904/df7a9be6-b08f-11e6-8e1d-e15a16f14df5.png)

**Comment by BallisticPain** [comment]
@jessepollak Is there a way in coffee script (I would guess so, I should look it up) to do something different for IE11 vs say Chrome which is what introduced this bug?

**Comment by kambanwait** [comment]
Pretty sure this is fixed in the latest version now - I had the same issue and raised a PR to remove the backface styling as you've mentioned

**Comment by LadyCarni** [comment]
This issue is coming up again in IE 11 btw.

![oct-20-2017 10-18-59](https://user-images.githubusercontent.com/6787230/31825429-3dbffae8-b580-11e7-8f15-477168ae6000.gif)

**Comment by melloware** [comment]
Can someone confirm is this is still happening in 2.5.0 latest version?

**Comment by melloware** [comment]
Working fine for me in IE11 in latest version
