### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by MonteShaffer** [jessepollak/card#299]
Luhn's check?

http://www.braemoor.co.uk/software/creditcard.shtml

MM/YY

CVC

Certainly I get "card" is a visual tool, but validation tied to the visual would be nice... change color to show error...

**Comment by BallisticPain** [comment]
@MonteShaffer 
Yes I think this would be a good idea. If you could also place the comment about the Luhn Javascript code you found that will be helpful to whomever can get around to adding this.

Thanks!

**Comment by jhernandes** [comment]
Hi!

I'm using the angular-version.

How can I get the object and check Cardtype, isValid or Not, etc?

Thanks!

**Comment by brondsem** [comment]
There is a library called `Payment` by the same author and I believe is embedded within the Card library release.  It sets `jp-card-invalid` or `jp-card-valid` classes on your inputs that you can style, or you can call the Payment functions directly: https://github.com/jessepollak/payment/#api
