### ISSUE TITLE
Rendering card with dynamically value doesn't work

### ISSUE THREAD

**Issue by jimblue** [jessepollak/card#306]
Hello

I have two inputs for my client name in a form:
- **firstname**
- **lastname**

I made a little script to automatically update the **name on card** with this two inputs.

A **trigger('input')** is fired on each changing value to be sure the **name on card** input is updated but still the corresponding text on **card.js** is not rendered.

It's seems that only a **TAB press** that focus on **name on card** input render the card.js. Even a **click** on this input didn't seems to work.

I've created a fiddle so you can see the problem:

Hope someone can help :)

Cheers

_this issue looks a bit like #184_

**Comment by chandler767** [comment]
You can use two inputs for the name on card by setting nameInput to your two fields. In your case, try this:
`nameInput: 'input[name="firstname"], input[name="lastname"]',`

**Comment by jmbelloteau** [comment]
Hey @chandler767,

Thanks for your fast answer!

But with your option you can't write a specific name for the card.  It can happen sometimes to pay with a card that have a different name from delivery address...

Any other idea?

**Comment by murilo3m** [comment]
I'm facing a similar problem. I'm using it on my checkout and when I choose the installment I need to do a quick refresh on the payment method div, but when I do so the CSS of the brand is lost and can't force the event to get the data again. I've tried focusing the field and simulate a key press event, but it didn't work.

If someone has a better idea or solution, please let me know.

**Comment by BallisticPain** [comment]
So I need the ability to have a different name with the card and the address on my form. I made an event that updated the card boxes as I typed into the first name box. However as has been pointed out, it didn't update on the card itself until I tabbed into the control.

**Comment by jmbelloteau** [comment]
anyone?

**Comment by BallisticPain** [comment]
Anyone able to submit a PR to expose an event and fix the updating?

**Comment by jmbelloteau** [comment]
bump !

**Comment by jmbelloteau** [comment]
nobody have an idea?

**Comment by jmbelloteau** [comment]
bump! anyone? :'(

**Comment by kevalmalde** [comment]
bump !

**Comment by hvaughan3** [comment]
See my answer and the entire thread [here](https://github.com/jessepollak/card/issues/355#issuecomment-372714338).

**Comment by CliqLabs** [comment]
Bump
