### ISSUE TITLE
How do I pre-set the card members name

### ISSUE THREAD

**Issue by tlykken** [jessepollak/card#308]
I have the card holders name and have it pre-populated in the form.  How do I set it in the Cart object?

**Comment by BallisticPain** [comment]
Good question, but it's possible as I have seen it be done recently... What have you tried already?
@theotherzach was the one that I know has made this work... perhaps they could share.

**Comment by kevalmalde** [comment]
I have a same question,
I have the card holders name and have it pre-populated in the form. How do I set it in the Cart object?

Things tried by me after creating card object
1. Triggered change, keyup, focus and blur event on card holder name input
2. Added and removed class .jp-card-flipped on .jp-card element

None of the above steps worked for me.

It would be great if some one guide me how to achieve this.
Thanks

**Comment by filippoaceto** [comment]
i need this feature

**Comment by david-sykora** [comment]
Hello,

i'm using this dirty solution. I'don't have time to search what events are triggering (propably keypress, keydown, blur, focus), so I use all possible events :) 

`            (function($) {
                $.fn.extend({
                    triggerAll: function (events, params) {
                        var el = this, i, evts = events.split(' ');
                        for (i = 0; i < evts.length; i += 1) {
                            el.trigger(evts[i], params);
                        }
                        return el;
                    }
                });
            })(jQuery);

            $('#cardModalName').val('tlykken').triggerAll(" blur  change  change  focus  select  submit  reset  keydown  keypress  keyup  keyup  keydown  keyup");`

**Comment by sizl** [comment]
anybody figure this out yet?

**Comment by hvaughan3** [comment]
See my answer and the entire thread [here](https://github.com/jessepollak/card/issues/355#issuecomment-372714338).

**Comment by CliqLabs** [comment]
Bump
