### ISSUE TITLE
Framework Versions of Card? Angular, React, Vue, Others?

### ISSUE THREAD

**Issue by BallisticPain** [jessepollak/card#310]
Are there any plans to make framework specific components of Card?
I think up to this point there haven't been any plans to do this, but I am looking at the possibility of an Angular version as I am currently working within that framework for my site... Using this as a tracker and see if there's interest from others.

I'll use comments below to add the varying frameworks that I'm aware of as being at least somewhat popular currently (feel free to add your own framework comment and thumbs up it). We likely won't be able to maintain a full list of framework components, but still want to see where the interest lies.

**Comment by BallisticPain** [comment]
Angular 1.x

**Comment by BallisticPain** [comment]
Angular 2+

**Comment by BallisticPain** [comment]
Ionic

**Comment by BallisticPain** [comment]
Vue

**Comment by BallisticPain** [comment]
Ember (linked in docs)

**Comment by caribnow** [comment]
I am trying to get it working with AngularJS and getting some strange errors. Did anyone have any luck?

**Comment by BallisticPain** [comment]
@caribnow Are you using the AngularJS version, or making your own? If you're using the AngularJS version, I would recommend posing issues with more descriptions about what you have tried and what "strange errors" actually are. Here's a link to the AngularJS version: https://github.com/gavruk/angular-card
I would have to say that people have had success. It has been forked and starred several times.

**Comment by hvaughan3** [comment]
Here is a Vue implementation (not one I have used before myself): [https://github.com/thiago-Malaca/vue-credit-card](https://github.com/thiago-Malaca/vue-credit-card)

**Comment by melloware** [comment]
All updated on the README.MD as well.
