### ISSUE TITLE
How do I set the card type upon initialization?

### ISSUE THREAD

**Issue by caribnow** [jessepollak/card#312]
I see how to set most of the values on the card, however the type is not clearly described. Any ideas?

**Comment by BallisticPain** [comment]
@caribnow 
I believe currently the card type is only calculated upon entry of the Card Number.

**Comment by at0dd** [comment]
You can do this with javascript by adding the `jp-card-[cardType] jp-card-identified` classes to the `.jp-card` element. For example, if the card is American Express the classes would be `jp-card-amex jp-card-identified`.
