### ISSUE TITLE
requiring card breaks with with browserfiy 

### ISSUE THREAD

**Issue by packytagliaferro** [jessepollak/card#314]
my vue core setup:

```
//Libraries
var $ 				= require("jquery")
window.jQuery 		= $;
var moment			= require('moment')
var card 			= require('card')

```

When I try and run gulp watch I get a `SyntaxError: Unexpected token`. If I remove the `var card 			= require('card')` it runs fine. Here is the area it breaks in my gulp file (think browserify is the issue)
```

gulp.task('browserify', function() {
    return browserify( site + 'resources/assets/js/vueCore.js')
        .transform(vueify)
        .bundle()
        //Pass desired output filename to vinyl-source-stream
        .pipe(source('bundle.js'))
        // Start piping stream to tasks!
        .pipe( gulp.dest( site + 'public/js/' ) );
  });

```

**Comment by BallisticPain** [comment]
I don't see anything incorrect... Just for laughs, have you tried putting semicolons at the end of each line instead of just the window.jQuery line? It shouldn't make a bit of difference, but I've not used Gulp much, and never used Vue so I can't offer much assistance on this.

My ignorance here... How does browserify know where to get Card? Does it use NPM in the background?

**Comment by redgeoff** [comment]
Unfortunately, it looks like card doesn't support browserify, just webpack. You may be able to use [browserify-css](https://github.com/cheton/browserify-css) or use the prebuilt files in the dist directory (found when installing via npm).

**Comment by jessepollak** [comment]
Can you try `var card = require('card/dist/card')`? Thanks!

**Comment by dunice-boldirev** [comment]
Hello jessepollak! I have tried way `var card = require('card/dist/card')` but I got error
`Error: Cannot find module '!!./../../node_modules/css-loader/index.js!./../../node_modules/sass-loader/index.js!./card.scss' from {path to project}/node_modules/card/dist `
