### ISSUE TITLE
Credit Card Skins

### ISSUE THREAD

**Issue by gsc-dev** [jessepollak/card#315]
More like a suggestion rather than an issue...

There are some really cool credit card skins with the code available here...

They would give an awesome look-and-feel for the lib!

http://codepen.io/robin-dela/pen/jVddbq

![image](https://cloud.githubusercontent.com/assets/18435451/21914093/db15039a-d928-11e6-9330-ae73a8fd767c.png)

**Comment by BallisticPain** [comment]
@gsc-dev 
Thanks for your suggestion. Those are some nice looking Visa cards. All of our cards are drawn via CSS (SCSS). So in order for us to consider something like this we would need it in that manner along with a PR integrating it and allowing theme picking. If you have time for this, I'm sure we would consider it.
