### ISSUE TITLE
Paste with mouse dont update card skin

### ISSUE THREAD

**Issue by arivanbastos** [jessepollak/card#318]
First, thank you for this great plugin!

When using right mouse button + Paste the card skin is not updated (the card company is not updated).
I fixed this changing the line 1599 from:

`QJ.on(el, 'keyup', setCardType);`

to

`QJ.on(el, 'keyup change', setCardType);`

**Comment by BallisticPain** [comment]
@arivanbastos 
Are you interested in submitting a PR and relate it to this issue? With a PR we would be able to swap to your branch and test it out.

Thanks!

**Comment by BallisticPain** [comment]
We would likely want something similar on each field btw. Not just one so the behavior is consistent throughout the fields.

**Comment by melloware** [comment]
Fixed in 2.5.0
