### ISSUE TITLE
Bourbon dependency

### ISSUE THREAD

**Issue by kenn** [jessepollak/card#319]
I'm using card via http://rails-assets.org and it errors out because of the following error.

```
Sass::SyntaxError: File to import not found or unreadable: bourbon/app/assets/stylesheets/bourbon
```

I had to pin the version to `0.1.4` so that I can make it work.

It's probably rails-assets's issue that doesn't support GIT submodule reference, but I also wondered if the dependency is light enough that there may be a possibility to remove the dependency.

I'm fine with `0.1.4` so far, but I thought it would be nice if we could catch up with the new version.

**Comment by jessepollak** [comment]
Thanks for opening up this issue! I believe that if you use the latest version and don't include the stylesheet in your `application.css` it will work fine. All styles are bundled with the javascript so there's no additional need to include that file. Please reopen if that doesn't work, thanks!

**Comment by kenn** [comment]
Awesome, it worked! Thank you! 🎉
