### ISSUE TITLE
CSS dist missing

### ISSUE THREAD

**Issue by finnp** [jessepollak/card#326]
Hey :)

love this project, really nice work! 

I noticed that the CSS-only example is not working anymore: https://jsbin.com/cinovupe/3/edit?html,output. It seems like there is no CSS file generated in the dist folder. It would be really nice if that could be added.

Best,
Finn

**Comment by BallisticPain** [comment]
@finnp Our documentation could definitely be more clear here. I have run into this issue myself, and found the answer hidden in our issues here. There are answers here we need to expose in the documentation, and I have a ticket started there.

**_ANSWER_**
**CSS is in the JavaScript File** there are no separate CSS dependencies.

It's all self contained for better or worse. So far it's worked wonders for me in multiple environments.

**Comment by BallisticPain** [comment]
I did look at your JSBin, and I didn't see where you had the JS file included. Maybe I'm unfamiliar with that interface.

**Comment by BallisticPain** [comment]
I'm closing this as it is not an actual issue. Hopefully I'll have time to create a documentation PR soon!

**Comment by jessepollak** [comment]
We should also just add the CSS as a separate `dist` asset so people who want to use just the CSS can. Should be relatively straightforward.

**Comment by mgildea** [comment]
would love to see a usable css dist! let me know if any help is needed if this effort is not already underway
