### ISSUE TITLE
Target element for CSS

### ISSUE THREAD

**Issue by svantetobias** [jessepollak/card#329]
I'm trying to use your excellent lib in my Web Component. Web Components are basically HTML+JS+CSS isolated in Shadow DOM's. The card source code seems to indicate that you write CSS to `document.head`, which does nothing for a Web Component.

Would it be possible to pass an element reference to `card` where the CSS will be written?
As I see it, this is the only thing missing from making `card` compatible with Web Components.

**Comment by BallisticPain** [comment]
That sounds reasonable. Is this something you can add via a PR? If not it'll be something we can try to get to in the future as we're adding functionality.

**Comment by melloware** [comment]
Card has been adapted in other Shadow DOM languages such as Vue, React, and Angular so I assume this is already possible.
