### ISSUE TITLE
Back card face disappear on CVC insert

### ISSUE THREAD

**Issue by juniormaciel** [jessepollak/card#341]
When CVC field selected, after card flip 1 second later, back face disappear and front face show as mirrored.
Including .jp-card.jp-card-flipped .jp-card-front{display:none;} to css rules can solve the problem.

**Comment by nancorrea** [comment]
Thanks! I got the same issue here this solved the problem!

**Comment by msj121** [comment]
Thanks, me too. I prefer this from I think the intended effect of having the front of the card show through with some type of opacity effect (that is my assumption of the original intention, or perhaps that was a bug too).

**Comment by melloware** [comment]
Can't reproduce in version 2.5.0
