### ISSUE TITLE
Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by SimplySynced** [jessepollak/card#342]
I've tried using both the jquery.card.js and the card.js files.  I've tried to include them at the bottom of the page.  I am trying to use this in a modal so I am wondering if this is the issue.  Here is my modal.

<div id="addCard" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<form id="card" class="form-horizontal form-label-left" method="POST">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
							</button>
							<h4 class="modal-title" id="myModalLabel">Add Contract </h4>
						</div>
						<div class="modal-body">
							<div class=".card"></div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="number">Credit Card Number:
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input type="text" id="number" name="number" required="required" class="form-control" placeholder="Credit Card Number" >
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="expiry">Expiration:
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input type="text" id="expiry" name="expiry" required="required" class="form-control" placeholder="MM/YY">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label colmd-3 col-sm-3 col-xs-12" for="name">Name: </label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input type="text" id="name" name="name" required="required" class="form-control" placeholder="Card Holder Name" >
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="cvv">CVV:
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input type="text" id="cvv" name="cvv" required="required" class="form-control" placeholder="" >
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
							<button type="submit" class="btn btn-primary" >Add Contract</button>
						</div>
					</form>
				</div>
			</div>
		</div>

and here is my script at the bottom of my php file.

<script type="text/javascript">
	new Card({
		form: 'form',
		container: '.card',
		formSelectors: {
			numberInput: 'input[name=number]',
			expiryInput: 'input[name=expiry]',
			cvcInput: 'input[name=cvv]',
			nameInput: 'input[name=name]'
		},

		width: 390, // optional — default 350px
		formatting: true,

		placeholders: {
			number: '•••• •••• •••• ••••',
			name: 'Full Name',
			expiry: '••/••',
			cvc: '•••'
		}
	})
</script>

As mentioned in the title I get the Cannot read property 'getAttribute' of undefined in the console.  Am I missing something?

**Comment by SimplySynced** [comment]
Hello, so I've done some more testing and this is what I've come up with.  When I use form it works fine but it doesn't seem to let me use names/ids/classes to choose the form.  Only when I remove the name/id/class does it work.  Is this something that can work or no?

**Comment by BallisticPain** [comment]
@SimplySynced 
I'm actually getting a similar error, and I'm hoping mine is simply because I wasn't using the CVC... however, I'm not setting the form selector, so not sure what our difference is to get the same error.

Thanks!

**Comment by BallisticPain** [comment]
@SimplySynced I believe my issue is related to using `*ngIf` and my elements don't exist yet...

**Comment by ziemerz** [comment]
I'm getting the same error. Also an Angular (4.x.x) application.

**Comment by muneer-memon** [comment]
@BallisticPain i have the same issue, if my element doesn't exist, it throws this error. Do we have the solution for this yet?

**Comment by stefmabo** [comment]
Any solution?

**Comment by muneer-memon** [comment]
you need to have all four fields on the form, if you wana skip any of them then you need to hide it. If you use *ngIf it wont render and it will complain.
in order to hide it you can use [hidden]="anyExpression"

**Comment by stefmabo** [comment]
Thanks @muneer-memon

**Comment by atakanaydin** [comment]
You need to add ID to the form

new Card({ form: 'form', ----> new Card({ form: '#formID',

**Comment by JoshuaNovak919** [comment]
I'm having this issues with normal Javascript and jQuery. Anyone solve this?

**Comment by hamedbaatour** [comment]
guys using Angular 5 just make sure to new up Card function in the ngAfterViewInit() lifecycle hook:

```
  ngAfterViewInit() {
    const card = new Card({
      form: '.card-form',
      container: '.card-wrapper',
    });
  }
```

@stefmabo @ziemerz

**Comment by jcjollant** [comment]
Same issue with Vue. Card() is invoked inside mounted() but it seems it's too soon.

**Comment by yankolo** [comment]
I had the same issue just now. I noticed I was loading the card before the DOM has loaded 🤣

**Comment by edlgg** [comment]
@jcjollant Do you know what do I need to do to make it work with Vue or Nuxt?
Im getting an error, TypeError: Cannot read property 'getAttribute' of undefined

This is the code I have:
```
<template>
  <form>
    <input type="text" name="number" />
    <input type="text" name="first-name" />
    <input type="text" name="last-name" />
    <input type="text" name="expiry" />
    <input type="text" name="cvc" />
  </form>
</template>

<script>
const cardData = {
  // a selector or DOM element for the form where users will
  // be entering their information
  form: 'card-form', // *required*
  // a selector or DOM element for the container
  // where you want the card to appear
  container: '.card-wrapper', // *required*

  formSelectors: {
    numberInput: 'input#number', // optional — default input[name="number"]
    expiryInput: 'input#expiry', // optional — default input[name="expiry"]
    cvcInput: 'input#cvc', // optional — default input[name="cvc"]
    nameInput: 'input#name' // optional - defaults input[name="name"]
  },

  width: 200, // optional — default 350px
  formatting: true, // optional - default true

  // Strings for translation - optional
  messages: {
    validDate: 'valid\ndate', // optional - default 'valid\nthru'
    monthYear: 'mm/yyyy' // optional - default 'month/year'
  },

  // Default placeholders for rendered fields - optional
  placeholders: {
    number: '•••• •••• •••• ••••',
    name: 'Full Name',
    expiry: '••/••',
    cvc: '•••'
  },

  masks: {
    cardNumber: '•' // optional - mask card number
  },

  // if true, will log helpful messages for setting up Card
  debug: true // optional - default false
}
export default {
  head() {
    return {
      script: [
        {
          src: 'node_modules/card/dist/card.js'
        }
      ]
    }
  },
  data: function() {
    return {
      card: null
    }
  },
  mounted() {
    const $ = require('jquery')
    window.jQuery = $
    console.log('window.jQuery: ', window.jQuery)
    const Card = require('card')
    console.log('card', Card)
    this.card = new Card(cardData)
  }
}
</script>
```

**Comment by muneer-memon** [comment]
> guys using Angular 5 just make sure to new up Card function in the ngAfterViewInit() lifecycle hook:
> 
> ```
>   ngAfterViewInit() {
>     const card = new Card({
>       form: '.card-form',
>       container: '.card-wrapper',
>     });
>   }
> ```
> 
> @stefmabo @ziemerz

You can also use ngOnChanges to initialize the card object.

**Comment by DerekCrosson** [comment]
> Same issue with Vue. Card() is invoked inside mounted() but it seems it's too soon.

I have the same problem, any idea how to fix it?

**Comment by hvaughan3** [comment]
@DerekCrosson We have our init call in `created` and within a `Vue.nextTick()` call.

**Comment by hounw** [comment]
was anyone able to fix this?????

**Comment by omansak** [comment]
Check this in your html `<div class='card-wrapper'></div>`

**Comment by hounw** [comment]
> Check this in your html `<div class='card-wrapper'></div>`

Yeah no, it is, but it needs to be inside it's own form for some reason in a woocommerce payment method.

I was able to fix it by creating a sub-form and then copying the element to hidden inputs inside the main woo form 🤷‍♂️

**Comment by marcos-alexandre82** [comment]
@hounw can you put in the gist and post here the code you used in WooCommerce? I'm having trouble implementing it on WooCommerce too.

**Comment by hounw** [comment]
@marcos-alexandre82 I was wrong I must've been something else that I ended up fixing, it CAN be inside a simple div.

the standard code worked for me, what issue are you facing?

**Comment by marcos-alexandre82** [comment]
@hounw are you using in a payment plugin for WooCommece?
I'm trying to implement it in my plugin, but it doesn't work properly. It only displays the skins of the Hipercard and Troy cards. If I try to use another card it remains gray.
For him to display the image of the card, I had to wrap the JS code with the jQuery function of WooCommerce, because otherwise, when the page is finished loading, the card disappears.

Can you help me?

These are the JS codes:
[card.js](https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/blob/development/assets/js/card.js)

[woo-rede.js](https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/blob/development/assets/js/woo-rede.js)

And this is the PHP code for the form:
[integration-rede-for-woocommerce.php](https://github.com/marcos-alexandre82/integration-rede-for-woocommerce/blob/development/integration-rede-for-woocommerce.php)

Tks

**Comment by hounw** [comment]
@marcos-alexandre82 that's weird... by instinct I'm pretty sure it's some other issue but here's how I ended up doing it... we only have mc/visa/amex so I don't know about all others but those three seem to work

https://gist.github.com/hounw/2083e9b3e252222ed55987c9d20f3579

**Comment by marcos-alexandre82** [comment]
@hounw Thank you! I will analyze your code and try to implement it in mine ;)

**Comment by melloware** [comment]
There are is now wrappers or documentation for Vue, Angular, React etc so closing this ticket

**Comment by guhenrique007** [comment]
> @jcjollant Do you know what do I need to do to make it work with Vue or Nuxt?
> Im getting an error, TypeError: Cannot read property 'getAttribute' of undefined
> 
> This is the code I have:
> 
> ```
> <template>
>   <form>
>     <input type="text" name="number" />
>     <input type="text" name="first-name" />
>     <input type="text" name="last-name" />
>     <input type="text" name="expiry" />
>     <input type="text" name="cvc" />
>   </form>
> </template>
> 
> <script>
> const cardData = {
>   // a selector or DOM element for the form where users will
>   // be entering their information
>   form: 'card-form', // *required*
>   // a selector or DOM element for the container
>   // where you want the card to appear
>   container: '.card-wrapper', // *required*
> 
>   formSelectors: {
>     numberInput: 'input#number', // optional — default input[name="number"]
>     expiryInput: 'input#expiry', // optional — default input[name="expiry"]
>     cvcInput: 'input#cvc', // optional — default input[name="cvc"]
>     nameInput: 'input#name' // optional - defaults input[name="name"]
>   },
> 
>   width: 200, // optional — default 350px
>   formatting: true, // optional - default true
> 
>   // Strings for translation - optional
>   messages: {
>     validDate: 'valid\ndate', // optional - default 'valid\nthru'
>     monthYear: 'mm/yyyy' // optional - default 'month/year'
>   },
> 
>   // Default placeholders for rendered fields - optional
>   placeholders: {
>     number: '•••• •••• •••• ••••',
>     name: 'Full Name',
>     expiry: '••/••',
>     cvc: '•••'
>   },
> 
>   masks: {
>     cardNumber: '•' // optional - mask card number
>   },
> 
>   // if true, will log helpful messages for setting up Card
>   debug: true // optional - default false
> }
> export default {
>   head() {
>     return {
>       script: [
>         {
>           src: 'node_modules/card/dist/card.js'
>         }
>       ]
>     }
>   },
>   data: function() {
>     return {
>       card: null
>     }
>   },
>   mounted() {
>     const $ = require('jquery')
>     window.jQuery = $
>     console.log('window.jQuery: ', window.jQuery)
>     const Card = require('card')
>     console.log('card', Card)
>     this.card = new Card(cardData)
>   }
> }
> </script>
> ```

me too, did you solve?

**Comment by ahinkle** [comment]
> There are is now wrappers or documentation for Vue, Angular, React etc so closing this ticket

Not everyone uses these frameworks. Seems like a valid issue.
