### ISSUE TITLE
Customize unknown card

### ISSUE THREAD

**Issue by dann95** [jessepollak/card#344]
Hi, is it possible change the color of the unknown card? 
thanks, Daniel

**Comment by Rigolon** [comment]
Hello Dann95, change the css like this.

.jp-card-unknown.jp-card .jp-card-front,
.jp-card-unknown.jp-card .jp-card-back {
        background: #7f4b9e;
}

![credit-card](https://cloud.githubusercontent.com/assets/2759081/25347688/21adec40-28f2-11e7-833e-1535acae62b4.PNG)

**Comment by dann95** [comment]
Hey, thanks ive been busy for perform that changes, but it works <3!
