### ISSUE TITLE
Show only last 4 digits in the visual card

### ISSUE THREAD

**Issue by georgetrad** [jessepollak/card#348]
Hi there,
How can I show only the last 4 digits in the visual card and keep the first digits as '•••••••' so the card would show something like this ••••••••••••5574

Thank you.

![capture](https://cloud.githubusercontent.com/assets/6954471/25676356/9bf38950-2ff6-11e7-80e0-da87fb627021.PNG)

**Comment by georgetrad** [comment]
@jessepollak Could you please help?

**Comment by andrewmbyrd** [comment]
@georgetrad 
when you're building your card, it looks like it helps to set the `masks` option:
```
<script>
        new Card({
            form: document.querySelector('form'),
            container: '.card-wrapper',
            masks: {
              cardNumber: '-'
            }
        });
    </script>
```
The `-` in the `cardNumber` above seems to work fine, but I'm sure you could get ••••• to show up depending on browser font and character recognition

**Comment by georgetrad** [comment]
@andrewmbyrd Thanks for the reply, but I know how to do that. What I need is to mask the first digits in the visual card and only show the last 4 digits.

**Comment by workgena** [comment]
This should help

https://github.com/jessepollak/card#usage-without-jquery

```js
var card = new Card({
 #...
  masks: {
    cardNumber: '•' // optional - mask card number. 
  },
 #...
});

```

It was merged by this PR #231

Also you can take a look at this snippet(patching distr-file, not good solution) https://github.com/jessepollak/card/issues/305#issuecomment-268293737

**Comment by georgetrad** [comment]
@workgena Thanks for your reply, but you gave me the same answer as @andrewmbyrd, and that's **not** what I'm looking for.
I need to mask all the numbers in the card **except for the last four digits**.

Thank you.

**Comment by georgetrad** [comment]
@workgena Thank you. That worked.

**Comment by georgetrad** [comment]
@andrewmbyrd Thank you. That was the solution but I didn't get it at first.
