### ISSUE TITLE
Not working when other Forms on page

### ISSUE THREAD

**Issue by kennycab1** [jessepollak/card#349]
I have other <form> </form> html code on the page that I wish to use card.js

When the script form is the only one on the page, the code works great.  However, if additional forms are on the same page, the code fails.

Does anyone have a fix for this?  

<body>
<div class='card-wrapper'></div>

<script src="/js/card.js"></script>

<form>
     <input type="text" name="other">
</form>

<form>
    <input type="text" name="number">
    <input type="text" name="name"/>
    <input type="text" name="expiry"/>
    <input type="text" name="cvc"/>
</form>
<script>

var card = new Card({
    form: 'form',
    container: '.card-wrapper',

    placeholders: {
        number: '**** **** **** ****',
        name: 'Arya Stark',
        expiry: '**/****',
        cvc: '***'
    }
});
</script>
</body>

**Comment by kennycab1** [comment]
I figured it out:

Give the form an id="<name>"

<form id="payment" >

Then in the script call the form with the id as such:
    <script>
        new Card({
            form: document.querySelector('#payment'),
            container: '.card-wrapper'
        });
    </script>

**Comment by lucymariej** [comment]
I know this has been closed for a while, just wanted to say thank you for this. I was banging my head against the wall for ages, and it didn't even think about checking the form selectors.
