### ISSUE TITLE
CSS only - Not working?

### ISSUE THREAD

**Issue by vanj** [jessepollak/card#353]
https://jsbin.com/cinovupe/3/edit?html,output

When I run this bin, the Output pane is not styled with the CSS. What am I missing?

Thanks

**Comment by BallisticPain** [comment]
Unless rawgit compiles the SCSS and such, there are NO css files within this project. All CSS is included in the JavaScript file.

**Comment by vanj** [comment]
Yes, I figured that out. I edited the JSBin to point the LINK tag to the new location and clicked Run but still no styles.

**Comment by Iyashu5040** [comment]
Yeah if you do a text search in the css file you'll find that none of the classes as they are used in the demo actually exist. Things like `mastercard` and `amex` simply aren't there. It looks like almost every class name has had `jp-card-` prepended to it.

Here's an example you can paste into the demo to see it working:
```
<div class="jp-card-container">
    <div class="jp-card jp-card-mastercard jp-card-identified">
        <div class="jp-card-front">
                <div class="jp-card-logo jp-card-visa">visa</div>
                <div class="jp-card-logo jp-card-mastercard">MasterCard</div>
                <div class="jp-card-logo jp-card-amex"></div>
                <div class="jp-card-logo jp-card-discover">discover</div>
            <div class="jp-card-lower">
                <div class="jp-card-shiny"></div>
                <div class="jp-card-cvc jp-card-display">••••</div>
                <div class="jp-card-number jp-card-display">5444 4444 4444 4444</div>
                <div class="jp-card-name jp-card-display">John Snow</div>
                <div class="jp-card-expiry jp-card-display">••/••</div>
            </div>
        </div>
        <div class="jp-card-back">
            <div class="jp-card-bar"></div>
            <div class="jp-card-cvc display">•••</div>
            <div class="jp-card-shiny"></div>
        </div>
    </div>
  </div>
```

Note: I changed the css src to `https://rawgit.com/jessepollak/card/master/dist/card.css`
