### ISSUE TITLE
New logo card provider

### ISSUE THREAD

**Issue by qdbdbp** [jessepollak/card#357]
Hello,
The Visa had a rebranding logo, the same Mastercard.
Would you upgrade according to the new logo?

http://www.underconsideration.com/brandnew/archives/new_logo_and_brand_positioning_for_visa.php

http://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_mastercard_by_pentagram.php

**Comment by iigmir** [comment]
Hi there, I just made a PR for this issue. Have a look at pull#359 .

**Comment by iigmir** [comment]
Hi @qdbdbp , do you want to close this issue since this issue was done?

**Comment by qdbdbp** [comment]
yes. job done :) txn
