### ISSUE TITLE
Card.prototype.handleInitialPlaceholders not works

### ISSUE THREAD

**Issue by letsspeak** [jessepollak/card#358]
I think there is two bugs in Card.prototype.handleInitialPlaceholders

- following el might be NodeList
  `el = this["$" + name];`

- following `el` in setTimeout always uses last value in for loop
```
	        results.push(setTimeout(function() {
	          return QJ.trigger(el, 'keyup');
	        }));
```

I just fixed this in my product, but I'm sorry that I'm not good at coffee :(
https://github.com/letsspeak/card/commit/d3cf0abfffd9dd4722ef10f3a531498a43df8c50

**Comment by melloware** [comment]
Fixed in 2.5.1
