### ISSUE TITLE
Allow rendered expiry year format to be configured (mm/yyyy vs. mm/yy)

### ISSUE THREAD

**Issue by iwootten** [jessepollak/card#36]
If would be great if when a form uses the format "mm/yyyy" for an expiry date, it could be displayed as four dots on the card.

I would do this myself, but haven't got time to learn coffeescript right now. :)

**Comment by jessepollak** [comment]
Thanks for the feedback :)

This is possible with the `values` option in the configuration — let me know if you have any issues with that!
