### ISSUE TITLE
IE8 got error "Object doesn't support this property or method"

### ISSUE THREAD

**Issue by DmytroStepaniuk** [jessepollak/card#361]
Cannt include query.card.js in ie8 because of the error that is related to following line: 

https://github.com/jessepollak/card/blob/master/dist/jquery.card.js#L692

in `addStyle` method

`update = applyToSingletonTag.bind(null, styleElement, styleIndex, false);`

So, actual question is - is it possible to fix it or get it working at least? :) Thx!

**Comment by melloware** [comment]
Closing as IE8 is no longer supported by MSFT.
