### ISSUE TITLE
Card Formatting doesn't work on Android Device

### ISSUE THREAD

**Issue by chris-snader** [jessepollak/card#362]
I found this when I went to test this awesome project on my personal Android device. I am running the very latest Android on my Nexus 5X.

**Comment by chris-snader** [comment]
`Payment.formatCardNumber = function(el) {
	      Payment.restrictNumeric(el);
	      QJ.on(el, 'keypress', restrictCardNumber);
	      QJ.on(el, 'keypress', formatCardNumber);
	      QJ.on(el, 'keydown', formatBackCardNumber);
	      QJ.on(el, 'keyup blur', setCardType);
	      QJ.on(el, 'paste', reFormatCardNumber);				
	      QJ.on(el, 'input', reFormatCardNumber);
	      return el;
	    };`

Adding the input action seems to fix the problem for the latest Android version. Saw this same fix for this issue on your Payment project. :)

**Comment by itruf** [comment]
Where u added this lines?

**Comment by walfridosp** [comment]
@chris-snader have you tried for Android 4.4? not working for me with the solution you provided. Thanks

@itruf, if you can to test the solution provided by @chris-snader, you can just search the function "Payment.formatCardNumber" in card.js file.

Thanks

**Comment by chris-snader** [comment]
@walfridosp I did not test on Android 4.4. Did that break the functionality for 4.4?

**Comment by walfridosp** [comment]
@chris-snader Actually, you solution did work. I also had to change the input type to "tel" to restrict user to enter only numbers, now I', trying to fix it for the Expiry (MM/YYYY) the '/' is not being added automatically and it allows any character, do you have a fix for this one? Thanks

**Comment by chris-snader** [comment]
@walfridosp For the expiration date I just did an HTML select for month and year.

**Comment by walfridosp** [comment]
@chris-snader At the end I just used one input field for each MM and YYYY and set both to type="tel" so far is working good! Thanks

**Comment by chris-snader** [comment]
@walfridosp no problem!

**Comment by melloware** [comment]
Workaround provided
