### ISSUE TITLE
Validation how-to

### ISSUE THREAD

**Issue by compgumby** [jessepollak/card#363]
I want to use this script in a project, but I'm not really clear on how validation works. Is this something that is automatically triggered by the form submit? Can this be done some other way?

**Comment by brondsem** [comment]
There is a library called `Payment` by the same author and I believe is embedded within the Card library release.  It sets `jp-card-invalid` or `jp-card-valid` classes on your inputs that you can style, or you can call the Payment functions directly: https://github.com/jessepollak/payment/#api
