### ISSUE TITLE
 Cannot set property 'Payment' of undefined

### ISSUE THREAD

**Issue by cyanpix** [jessepollak/card#365]
I am using webpack with Babel. When I am trying to import card.js I getting this error. Any suggestions?

![image](https://user-images.githubusercontent.com/11429236/27771677-0b3c841a-5f54-11e7-9963-5d8734a275e1.png)
![image](https://user-images.githubusercontent.com/11429236/27771678-114f03e6-5f54-11e7-8913-b8357b52cdac.png)

**Comment by SamuelKnoch** [comment]
Do you tried:
`import * as Card from './../plugins/card.js`

**Comment by hvaughan3** [comment]
Did anyone ever figure this out? I tried @SamuelKnoch 's suggestion and am still getting the same issue. I also tried manually installing the the Payment npm package and including the payment.js file.

**Comment by bok04** [comment]
@hvaughan3  could you explain what you did to get it working? I'm trying to get this to work with VueJs but I'm finding a similar issue at the moment.

**Comment by hvaughan3** [comment]
@bok04 

Sure thing. I just added the following into my webpack.base.conf:

    module.exports = {
      ....
      plugins: [
        new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: 'jquery',
          Card: 'card'
        })
      ],

**Comment by bok04** [comment]
@hvaughan3 Thank you so much! I have this working now

**Comment by DerekCrosson** [comment]
> @bok04
> 
> Sure thing. I just added the following into my webpack.base.conf:
> 
> ```
> module.exports = {
>   ....
>   plugins: [
>     new webpack.ProvidePlugin({
>       $: 'jquery',
>       jQuery: 'jquery',
>       Card: 'card'
>     })
>   ],
>   ....
> }
> ```

Any idea how to do this with Vue CLI 3?

This is what I have:
```
module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        Card: 'card'
      })
    ]
  },
  pluginOptions: {
    i18n: {
      locale: "en",
      fallbackLocale: "en",
      localeDir: "locales",
      enableInSFC: false
    }
  }
};
```
The bottom part is for localisation.

I get the following error in the console and page is blank:
```
vue-router.esm.js?8c4f:1897 TypeError: Cannot set property 'Payment' of undefined
    at Object.eval (card.js?0498:1622)
    at Object.eval (card.js?0498:1624)
    at Object.eval (card.js?0498:1626)
    at __webpack_require__ (card.js?0498:21)
    at Object.eval (card.js?0498:55)
    at Object.eval (card.js?0498:396)
    at __webpack_require__ (card.js?0498:21)
    at eval (card.js?0498:41)
    at eval (card.js?0498:42)
    at Module../src/assets/js/card.js (account.js:35)
```

**Comment by DerekCrosson** [comment]
> > @bok04
> > Sure thing. I just added the following into my webpack.base.conf:
> > ```
> > module.exports = {
> >   ....
> >   plugins: [
> >     new webpack.ProvidePlugin({
> >       $: 'jquery',
> >       jQuery: 'jquery',
> >       Card: 'card'
> >     })
> >   ],
> >   ....
> > }
> > ```
> 
> Any idea how to do this with Vue CLI 3?
> 
> This is what I have:
> 
> ```
> module.exports = {
>   configureWebpack: {
>     plugins: [
>       new webpack.ProvidePlugin({
>         $: 'jquery',
>         jQuery: 'jquery',
>         Card: 'card'
>       })
>     ]
>   },
>   pluginOptions: {
>     i18n: {
>       locale: "en",
>       fallbackLocale: "en",
>       localeDir: "locales",
>       enableInSFC: false
>     }
>   }
> };
> ```
> The bottom part is for localisation.
> 
> I get the following error in the console and page is blank:
> 
> ```
> vue-router.esm.js?8c4f:1897 TypeError: Cannot set property 'Payment' of undefined
>     at Object.eval (card.js?0498:1622)
>     at Object.eval (card.js?0498:1624)
>     at Object.eval (card.js?0498:1626)
>     at __webpack_require__ (card.js?0498:21)
>     at Object.eval (card.js?0498:55)
>     at Object.eval (card.js?0498:396)
>     at __webpack_require__ (card.js?0498:21)
>     at eval (card.js?0498:41)
>     at eval (card.js?0498:42)
>     at Module../src/assets/js/card.js (account.js:35)
> ```

Added ```const webpack = require("webpack");``` above but still getting the error.

**Comment by SamuelKnoch** [comment]
> ...
> Added `const webpack = require("webpack");` above but still getting the error.

Is not required here.

It seems that the card.js is found but 'Payment' does not exist in this class. So is payment installed via npm? Can you please post here some code where you reference the 'Card' in VUE

**Comment by DerekCrosson** [comment]
> > ...
> > Added `const webpack = require("webpack");` above but still getting the error.
> 
> Is not required here.
> 
> It seems that the card.js is found but 'Payment' does not exist in this class. So is payment installed via npm? Can you please post here some code where you reference the 'Card' in VUE

I added the files from the dist folder to my project and I'm calling it like this:
``` import Card from "@/assets/js/card.js"; ```

I'm not sure if this is correct? Should I install it using npm? If I use npm would I have to use jQuery too? I'm trying not to use jQuery in this project.

**Comment by SamuelKnoch** [comment]
If you use only the card.js file you have to look up in this file. In this file there is an import from payment so if you have not installed card over npm you have not all the dependencies.

**Comment by DerekCrosson** [comment]
> If you use only the card.js file you have to look up in this file. In this file there is an import from payment so if you have not installed card over npm you have not all the dependencies. JQuery is not required if you only use the card.js

Finally got it working, I installed the npm package and was still having some issues but when I removed all the optional parameters it just worked :-D

Thanks, @SamuelKnoch! Appreciate your help :)

**Comment by melloware** [comment]
Vue.js instructions are now provided: https://github.com/jessepollak/card#vue

Closing this ticket as workarounds have been provided.
