### ISSUE TITLE
Support for Angular 2

### ISSUE THREAD

**Issue by iosdroid** [jessepollak/card#366]
It's possible using this library for angular 2

**Comment by brunosoaresds** [comment]
@iosdroid,

I'm using in Angular 2, however i added the library manually, i got card.js, paste on assets directory and included it in the index.html. To use i have made:

`let card = new (<any>window).Card({
      form: 'form.cardform',
      container: '.card-wrapper',
      messages: {
        validDate: 'GOOD\nTHRU',
        monthYear: 'mm/aaaa'
      },
      placeholders: {
        number: '•••• •••• •••• ••••',
        name: 'Nome Completo',
        expiry: '••/••',
        cvc: '•••'
      }
    });`

**Comment by iosdroid** [comment]
@brunosoaresds  Thanks.. Once I try with this let u know
