### ISSUE TITLE
How to get cardtype after fill the card number?

### ISSUE THREAD

**Issue by expert-it** [jessepollak/card#370]
I want to get the cardtype after fill the detail of card number , there is any callback or function which I have used to get cardtype

**Comment by setheryb** [comment]
I second this question

**Comment by nick-fytros** [comment]
```js
const cardObject = new Card({
    form: '#card-form', // *required*
    container: '.card-wrapper', // *required*
});
// log the card type
console.log(cardObject.cardType);
```

**Comment by hvaughan3** [comment]
You can also use the Payment APIs built into card.js:

    var cardType = global.Payment.fns.cardType('41') // Returns "visa"

**Comment by deepcell** [comment]
I does not work.
