### ISSUE TITLE
Stripe.js v3

### ISSUE THREAD

**Issue by MillerApps** [jessepollak/card#372]
How would one integrate this with Stripe.js v3?

**Comment by MillerApps** [comment]
Well, as it turns out it is not possible using v3. Here is what I was told by Stripe support. 

Due to the way Elements works, you cannot get the card numbers into your frontend Javascript in order to use with a component such as Card. Doing so exposes you to a stricter set of PCI requirements.

We've designed Elements as the best way to build customized payment flows that are both secure and optimized for conversion. We will use Elements as the base to launch more improvements, including support for more payment methods, better fraud detection, and more. In addition to those benefits, if you use Stripe Elements, you'll continue to be eligible for the simplest PCI validation method, Self-Assessment Questionnaire A (SAQ A).

For some context, the PCI Council has published a series of changes to eligibility requirements for SAQ A. These require that businesses use input fields hosted by a payments provider in order to be eligible for SAQ A. We've designed Elements with these changes in mind so that you can continue to validate using SAQ A without losing much of the flexibility and customizability of a form hosted on your website. You are absolutely right, though, that there can be some compromise when it comes to customizability with this approach.[1]

That being said, you can continue using Stripe.js/v2 as we will continue to support it indefinitely. However, please note that you'll need to start validating your PCI compliance annually using the long-form PCI Self-Assessment Questionnaire A-EP (SAQ A-EP) [2]. There may be additional security controls to implement to validate PCI compliance using SAQ A-EP. The changes you might need to make will depend on your current security practices.

If you choose to continue with Stripe.js/v2 and you need help filling out the SAQ A-EP, we can put you in touch with one of our preferred PCI Qualified Security Assessors (QSA) who deeply understands the various Stripe integration methods.

I hope this helps. If you've any further questions or concerns, please do let me know.



[1] https://stripe.com/docs/security#validating-pci-compliance
[2] https://www.pcisecuritystandards.org/documents/PCI-DSS-v3_2-SAQ-A_EP.pdf

**Comment by LeebranZadwell** [comment]
Hey Tyler,

You can somewhat fudge it (I'm using a different payment processor but a similar setup)

Essentially, you won't be able to populate the "card" with any values outside of the card holder name. Instead, using the events that the script exposes, you can adjust the brand, and flip the card when the user focuses/blurs on the cvc field. It's not perfect, but a decent compromise.

To select a brand (assuming jquery here:)

$('.jp-card').addClass('jp-card-identified');
$('.jp-card').addClass('jp-card-' + CARD_BRAND);

Flipping the card to the back-side follows a similar pattern. (The class is "jp-card-flipped")

You still get a nice card, and you can even have the elements on the card light up when the user focuses and blurs the respective fields. And you still get SAQ-A!

Just my two cents, hope that helps someone!

https://stripe.com/docs/stripe.js#element-on

**Comment by brianradke** [comment]
Hey Leebran, thanks for posting that, took me a while to figure out that it's not going to work with v3. Any chance you can post your solution/fudge in context? I'm having difficulty getting it working. Thanks!!

**Comment by brianradke** [comment]
Anyone? I know I'm not the only person who's going to have this issue ;)

**Comment by Nurrl** [comment]
Hi @brianradke, I'm experiencing the same issue, and the issue comes from Stripe V3 API, the form is inside an iframe.

**Comment by brianradke** [comment]
Hi @Nurrl, yep, I couldn't find an adequate workaround to this so I held off on implementing card for now. I understand that it's an issue with getting the card number as @MillerApps said but maybe card could be updated to be more V3 friendly? Making it behave like @LeebranZadwell described here would be acceptable for me (just omitting the card number entry feature) but I was unable to get it to work :/

**Comment by LeebranZadwell** [comment]
Hi @brianradke,

Sorry I haven't checked my notifications in a long while.

There won't be an update to card in all likelihood. The reason companies like Stripe and Bambora (what I use) have done this is so your PCI liability is reduced. If we could access that data, then it would defeat the point of their implementation. This is very intentional on their part!

So here are the steps to highlight the fields on the card as the user is filled out your form. Most of the values will not populate on the card (but you can still highlight the card, and flip it when appropriate.)

I'm going to assume you have "mounted" your fields to the payment script. Also, the syntax will vary since I am using a different payment script. I don't know the exact format Stripe uses.

# Selecting a Brand on Card Using JQuery
**CARD_BRAND** is a javascript variable you'll need to define on your own.
`$('.jp-card').addClass('jp-card-identified');
$('.jp-card').addClass('jp-card-' + CARD_BRAND);`
# Highlighting Fields on Card
While your user is filling out values, we can't determine the values - but we can determine which field is being focused.

`  /*
   * This event allows us to interact with the big card.
   */
  checkout_script.on('focus', function(event) {
    if ( event.field === 'cvv' ) {
      $('.jp-card').addClass('jp-card-flipped');
      $('.jp-card-cvc').addClass('jp-card-focused');
    }

    if ( event.field === 'expiry' ) {
      $('.jp-card-expiry').addClass('jp-card-focused');
    }

    if ( event.field === 'card-number' ) {
      $('.jp-card-number').addClass('jp-card-focused');
    }
  });`

Do the same for the **blur** event. Focusing the CVV field in your payment form also triggers the card flipping. The blur also handles unflipping the card. As far as cardholder name is concerned - you can hook it up directly to the animated Card for it to populate. Depending on Stripe gives you the brand, you'll need to brand the card in a similar fashion. Boom, it's not perfect, but it can look intentional!

Hope that helps. I recommend diving into the documentation if you're having further issues:

https://stripe.com/docs/stripe.js#element-on
https://github.com/jessepollak/card/blob/master/dist/jquery.card.js#L393

**Comment by DeoluA** [comment]
Hi @LeebranZadwell 

Sadly I don't think this workaround is still supported by Stripe right now. As far as I can tell, the latest change is that the `focus` event now no longer emits any `field` properties, and the only `field` property passed to the `change` event is just `brand`.

So now:
```
// focus event
checkout_script.on('focus', function(event) {
    console.log( event.field ) // <-- this yielded 'undefined' for me
})

// change event
checkout_script.on('change', function(event) {
    console.log( event.field ) // <-- this yielded 'undefined' still
    console.log( event.brand ) // <-- this yielded the brand, as expected
})
```

Thankfully there is yet another hack though: _Stripe still passes the **error** messages_. It's not clean, but using this could still work:

```
// change event, using error messages
checkout_script.on('change', function(event) {
      if ( event.error !== undefined && event.error.code.toLowerCase() === 'incomplete_number' ) {
          console.log( "User is currently entering/changing their card number. Highlight on Card")
      };
      if ( event.error !== undefined && event.error.code.toLowerCase() === 'incomplete_expiry' ) {
          console.log( "User is currently entering/changing their expiry date. Highlight on Card")
      };
      if ( event.error !== undefined && event.error.code.toLowerCase() === 'incomplete_cvc' ) {
          console.log( "User is currently entering/changing their CVC. Highlight on Card")
      };
})
```

The above example is not the cleanest of hacks, but I do hope it helps as pointer in the right direction for someone else who may stumble on to this.

You'll have to look through other possible error codes that Stripe could throw to come up with something more robust:

https://stripe.com/docs/error-codes

All the best!

**Comment by PriceFallin** [comment]
@DeoluA,

The 'change' event for Stripe v3 only fires for 4 types of events:
- Card brand changes
- An error exists after input an input is blurred (not on keyup)
- Postal code change (on keyup)
- Card info is complete or empty

Unfortunately, I was not able to use the errors to detect which input field the user is focused in, other than the postal code. The only time the errors give you a good indication of this is if the input is blurred with an error remaining in the input value.

I'll keep messing around and report back if I can figure out another solution.

**Comment by DeoluA** [comment]
Hi @PriceFallin 

I hope you have a better outcome than I did. You're right about the `blur`: what I ended up settling for was only using `card.js` as a visual guide for the user if they happened to make an error _after_ they filled any of the inputs, viz:

```
// checking
var card_errors = ["incomplete_number", "invalid_number"];
var expiry_errors = ["incomplete_expiry", "invalid_expiry_month_past", "invalid_expiry_year_past"];
var cvc_errors = ["incomplete_cvc", "invalid_cvc", "incorrect_cvc"];

stripe_card.on('change', function(event){
      // monitor the brand
      var cardLogo = 'none';
      var card_class = 'unknown';

      if (event.brand && event.brand !== 'unknown') {
            var filePath = 'https://cdn.na.bambora.com/downloads/images/cards/' + event.brand + '.svg';
            cardLogo = 'url(' + filePath + ')';

            card_class = 'jp-card-' + event.brand;

            $('.jp-card').attr('class', 'jp-card');
            $('.jp-card').addClass('jp-card-identified');
      };

      if ( card_class === 'unknown' ) {
            $('.jp-card').removeClass('jp-card-identified');
      };

      $('.jp-card').addClass(card_class);

      // highlight all initially
      $('.jp-card-name').addClass('jp-card-focused');
      $('.jp-card-number').addClass('jp-card-focused');
      $('.jp-card-expiry').addClass('jp-card-focused');
      $('.jp-card-cvc').addClass('jp-card-focused');

      // if there's an error with the card number input, let them know after blur by dimming its input
      if ( event.error !== undefined && card_errors.indexOf(event.error.code.toLowerCase()) > -1 ) {
            $('.jp-card').removeClass('jp-card-flipped');
            $('.jp-card-number').removeClass('jp-card-focused');
      };
      // ...error with the expiry input, let them know after blur...
      if ( event.error !== undefined && expiry_errors.indexOf(event.error.code.toLowerCase()) > -1 ) {
            $('.jp-card').removeClass('jp-card-flipped');
            $('.jp-card-expiry').removeClass('jp-card-focused');
      };
      // error with the cvc...
      if ( event.error !== undefined && cvc_errors.indexOf(event.error.code.toLowerCase()) > -1 ) {
            $('.jp-card').addClass('jp-card-flipped');
            $('.jp-card-cvc').removeClass('jp-card-focused');
      };
});
```

The above, again, is not a complete and total solution, but it was enough to suffice for my case. Stripe v3 does a good job of not letting you know card details as they're being inputted - which is what it's _supposed_ to do anyway. Just a bit sad that it's causing this workaround. Perhaps there should be a new warning/disclaimer added to the `card.js` documentation for anyone who may want to use this with Stripe v3?

Anyway, hope my method above works, or at least sheds more light towards a better one. Also hoping you're more successful @PriceFallin ! 🤞
