### ISSUE TITLE
Input Type "number"

### ISSUE THREAD

**Issue by anderlin** [jessepollak/card#373]
Hi,
we want to integrate an input type "number" for the credit card number and expiry date. The reason is that we want to force the numeric keyboard on mobile devices. Unfortunately this is not possible at the time, cause the digits inside the input are deleted by the card. Maybe there is another way or something else? Or is this absolutely not possible?

Thank you for your Help

**Comment by LadyCarni** [comment]
Have you tried turning off the auto-formatting option that comes with this? 

`formatting={false}`

I tested doing that and running my own validation for integers only and that seemed to work. That might work toward what you're trying to achieve.
