### ISSUE TITLE
Hipercard compatibility

### ISSUE THREAD

**Issue by leonardothibes** [jessepollak/card#378]
Can someone add a Hipercard compatibility? Hipercard is a type of Brazillian credit card.

For more information, see here https://www.npmjs.com/package/creditcard-identifier

**Comment by fabiomtl** [comment]
This would be great!

**Comment by luizdesign** [comment]
The Hipercard number is accepted already, but haven't a skin to card. 
I need this skin and I'm wonking in this skin at the moment.
