### ISSUE TITLE
Update JCB pattern and format

### ISSUE THREAD

**Issue by capitaladot** [jessepollak/card#384]
Card Brand | Low Range | High Range | PAN Length
-- | -- | -- | --
JCB | 35280000 | 35899999 | 10 -19
JCB Effective April 2022 | 30880000 | 30940000 | 10 -19
JCB Effective April 2022 | 30960000 | 31029999 | 10-19
JCB Effective April 2022 | 31120000 | 31209999 | 10-19
JCB Effective April 2022 | 31580000 | 31599999 | 10-19
JCB Effective April 2022 | 33370000 | 33499999 | 10-19

**Comment by melloware** [comment]
Fixed with: https://github.com/jessepollak/card/pull/458
