### ISSUE TITLE
Firefox mobile browser problem, exp date

### ISSUE THREAD

**Issue by adamus007p** [jessepollak/card#387]
I was testing with different phones, android and iphones.
The problem is with javascript and fields.
In firefox I need to use a “space” to have a exp date as 12/19
In other case there is 1219 / which give an error.

on Firefox PC browser everything works
on Chrome PC browser everything works
on Firefox mobile browser problems
on Chrome mobile browser everything works

on Firefox mobile browser I can use space and enter exp date using enter and pay, but it is no user friendly as also nobody know about it.

That problems are only with Firefox on mobile phone.
Please install firefox on you mobile and check it by yourself.
Do not use a mobile version on Chrome or any PC emulators, just a phone.

**Comment by adamus007p** [comment]
updated

**Comment by nellysattari** [comment]
same problem for me, any solution?

**Comment by faizan-peerbits** [comment]
For others
Just change the type "text" to "tel" which will work

https://github.com/jessepollak/card/issues/199

**Comment by melloware** [comment]
I believe instead of `type="tel"` you should be able to use HTML5 `inputmode` which tells which vritual keyboard to use in mobile browsers.  So `<input type="text" inputmode="numeric" />`
