### ISSUE TITLE
card.js in MVC5  Cshtml

### ISSUE THREAD

**Issue by vinith351** [jessepollak/card#388]
Card can't find a numberInput in your form.
Card can't find a expiryInput in your form.
 Card can't find a cvcInput in your form.
 Card can't find a nameInput in your form.

I got these errors when i tried to implement credit payment. I followed the same steps as described. I was not able to degub the core issue. can you help me

**Comment by atakanaydin** [comment]
are the input names the same? Can you share your code please.

**Comment by vinith351** [comment]
<div class="body-text">Try to write your name in the name fields. Also try to write your card number. This plugin identifies your card and shows the right graphics. By clicking CCV field card will turn.</div>
<form>
    <div class="form-container">
    <div class="personal-information">
        <h1>Payment Information</h1>
    </div>
    

    <input id="input-field" type="text" name="streetaddress" required="required" autocomplete="on" maxlength="45" placeholder="Streed Address" />
    <input id="column-left" type="text" name="city" required="required" autocomplete="on" maxlength="20" placeholder="City" />
    <input id="column-right" type="text" name="zipcode" required="required" autocomplete="on" pattern="[0-9]*" maxlength="5" placeholder="ZIP code" />
    <input id="input-field" type="email" name="email" required="required" autocomplete="on" maxlength="40" placeholder="Email" />

    <div class="card-wrapper"></div>
    <input id="column-left" type="text" name="first-name" placeholder="First Name" />
    <input id="column-right" type="text" name="last-name" placeholder="Surname" />
    <input id="input-field" type="text" name="number" placeholder="Card Number" />
    <input id="column-left" type="text" name="expiry" placeholder="MM / YY" />
    <input id="column-right" type="text" name="cvc" placeholder="CCV" />
    <input id="input-button" type="submit" value="Submit" /></div>
</form>

<link href="~/Content/card.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/card.js"></script>

<script type="text/javascript">
    $('form').card({
        // a selector or DOM element for the container
        // where you want the card to appear
        container: '.card-wrapper', // *required*
  formSelectors: {
        nameInput: 'input[name="first-name"], input[name="last-name"]'
    }
        // all of the other options from above
    });
</script>
<style type="text/css">
    body {
        padding: 60px 0px;
        background-color: #B2D1E5;
        margin: 0 auto;
        width: 600px;
    }
    .body-text {
        padding: 0 20px 30px 20px;
        font-family: "Roboto";
        font-size: 1em;
        color: #fff;
        text-align: center;
    }
    .form-container {
        width: 100%;
    }
    .card-wrapper {
        background-color: #6FB7E9;
        padding: 10px 0px;
        width: 100%;
    }
    .personal-information {
        background-color: #3C8DC5;
        color: #fff;
        padding: 1px 0px;
        text-align: center;
    }
    h1 {
        font-size: 1.3em;
        font-family: "Roboto"
    }
    input {
        margin: 1px 0px;
        padding-left: 3%;
    }
    input[type="text"]{
        display: block;
        height: 50px;
        width: 97%;
        border: none;
    }
    input[type="email"]{
        display: block;
        height: 50px;
        width: 97%;
        border: none;
    }
    input[type="submit"]{
        display: block;
        height: 60px;
        width: 100%;
        border: none;
        background-color: #3C8DC5;
        color: #fff;
        margin-top: 2px;
        cursor: pointer;
        font-size: 0.9em;
        text-transform: uppercase;
        font-weight: bold;
    }
    input[type="submit"]:hover{
        background-color: #6FB7E9;
        transition: 0.3s ease;
    }
    #column-left {
        width: 46.8%;
        float: left;
        margin-bottom: 2px;
    }
    #column-right {
        width: 46.8%;
        float: right;
    }

    @@media only screen and (max-width: 480px){
    body {
        width: 100%;
    }
    .form-container {
        width: 100%;
    }
    h1 {
        font-size: 1.2em;
    }
    input {
        margin: 2px 0px;
    }
    #input-field {
        width: 100%;
    }
    input[type="text"]{
        height: 40px;
    }
    input[type="email"]{
        height: 40px;
    }
    input[type="submit"]{
        height: 50px;
    }
    #column-left {
        width: 100%;
        display: block;
        float: none;
    }
    #column-right {
        width: 100%;
        display: block;
        float: none;
    }
    #input-button {
        width: 100%;
    }
    }
</style>

**Comment by vinith351** [comment]
I followed this site and the code is exact same as here..  https://codepen.io/hswd/pres/JYvgBW
![capture](https://user-images.githubusercontent.com/34749720/34312872-25fa1506-e735-11e7-82bd-a98ec8289f4c.PNG)

**Comment by vinith351** [comment]
I tried using jquery.card.js which is not giving me any exceptions but the issue is it not reading input values. Does the form input need to be changed if i use jquery.card.js?

**Comment by vinith351** [comment]
Now i realized when i got latest code. Initially i got card.js from nuget pacakage which seems very different from  the folder https://github.com/jessepollak/card/tree/master/dist. Now i am not getting any errors but issue is **input form keypress** is not recognized.

**Comment by melloware** [comment]
Please try latest version 2.5.0
