### ISSUE TITLE
How to add in project using Webpack

### ISSUE THREAD

**Issue by GetTaxSolutions** [jessepollak/card#393]
Do you have some instructions how can add the Card object using Webpack?

Thank you

**Comment by hvaughan3** [comment]
I was able to get it working by using the ProviderPlugin. After installing the card js NPM library, add the following to your webpack.base.conf or where ever:
    new webpack.ProvidePlugin({
      $: 'jquery', // This may not be needed for you
      jQuery: 'jquery', // This may not be needed for you
      Card: 'card'
    })

Now everywhere you reference `Card` in your project, Webpack will substitute the Card JS reference
