### ISSUE TITLE
How can I get a input with the card type filled.

### ISSUE THREAD

**Issue by gabrieljadeau** [jessepollak/card#396]
Hi,

I would like to be able to fill an input with the card type. Could you please let me know if it's possible at the moment??

Best,

Gabriel

**Comment by RupW** [comment]
Yes: when it identifies the card type, the code triggers an event 'payment.cardType' on the card number input box, and the event detail field is the card type. You can add an event handler to the field, catch this event and then save the value in your hidden input.

(However note that jQuery treats dots in event names as namespaces, meaning you'll have to use some other mechanism, e.g. addEventListener directly, to set up the event. AFAICS it's not possible to bind to event 'payment.cardType' using jQuery.)

**Comment by gabrieljadeau** [comment]
Hi, thanks for that. I already did it .

Best

Gabriel
