### ISSUE TITLE
expiry year and month

### ISSUE THREAD

**Issue by azisyus** [jessepollak/card#399]
what about separating these fields or making them separate is optional? we just dont want to parse these dates after post, i think card data should be pass directly to bank or is this feature already exists and am i missing it?

**Comment by azisyus** [comment]
i figure out myself

**Comment by hedii** [comment]
@azisyus please show your solution

**Comment by azisyus** [comment]
@hedii 
expiryInput has 2 different input and as you can see; you should match with input names
` <script>

        var card = new Card({
            form: 'form',
            container: '.card-wrapper',

            formSelectors:{
                nameInput: 'input[name="cardholder"]',
                expiryInput: 'input[name="cardexpiredatemonth"], input[name="cardexpiredateyear"]',
                cvcInput: 'input[name="cardcvv2"]',
                numberInput: 'input[name="cardnumber"]'

            },

            placeholders: {
                number: '**** **** **** ****',
                name: 'Arya Stark',
                expiry: '**/**',
                cvc: '***'
            },
            debug: false

        });

        $('#month').mask('00');
        $('#year').mask('00');
    </script>`

**Comment by hedii** [comment]
@azisyus thanks
