### ISSUE TITLE
card doesn't rotate on cvc typing after pasting credit card number

### ISSUE THREAD

**Issue by michelemilani91** [jessepollak/card#402]
i tried to paste my credit card number on the form but that block the credit card animation (rotation).
the rotation works just typing numbers on the field.

**Comment by AliRaxaa** [comment]
The same problem am facing, did you find any solution?

**Comment by melloware** [comment]
Are you using the latest version of card found here: https://github.com/jessepollak/card/tree/master/dist

**Comment by AliRaxaa** [comment]
Yes, am are using the latest version, it seems like any resource, is there any specific file to include to perform card rotate animation?

**Comment by melloware** [comment]
Is it rotating on other fields just not when you enter the CVC? 

Can you try this running example: https://www.primefaces.org/showcase-ext/sections/creditcard/basicUsage.jsf

Does it flip for you there?  as soon as I tab into CVC it flips.
