### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by joecutter** [jessepollak/card#405]
Am getting this error " Uncaught ReferenceError: jQuery is not defined "

<img width="718" alt="screen shot 2018-06-21 at 3 31 00 pm" src="https://user-images.githubusercontent.com/11267062/41719308-5ed6f3fa-7568-11e8-8309-cdb4682c03a9.png">

my code snippet

  /** CARD API*/
      $('formcard').card({
        // form: 'formcard', // *required*
        container: '.card-wrapper',

        formSelectors: {
           numberInput: 'input[name="number"]', // optional — default input[name="number"]
           expiryInput: 'input[name="expiry"]', // optional — default input[name="expiry"]
           cvcInput:    'input[name="cvc"]', // optional — default input[name="cvc"]
           nameInput:   'input[name="first-name"], input[name="last-name"]' // optional - defaults input[name="name"]
       },

       width: 200, // optional — default 350px
       formatting: true, // optional - default true

       // Strings for translation - optional
       messages: {
           validDate: 'valid\ndate', // optional - default 'valid\nthru'
           monthYear: 'mm/yyyy', // optional - default 'month/year'
       },

       // Default placeholders for rendered fields - optional
       placeholders: {
           number: '•••• •••• •••• ••••',
           name: 'Full Name',
           expiry: '••/••',
           cvc: '•••'
       },

       masks: {
           cardNumber: '•' // optional - mask card number
       },

       // if true, will log helpful messages for setting up Card
       debug: false // optional - default false
     });

**Comment by hvaughan3** [comment]
I think I also ran into this issue and fixed it using the webpack `ProviderPlugin`. I added the following to my **webpack.base.conf.js** file:

    ...

    module.exports = {
        ...
        plugins: [
            new webpack.ProvidePlugin({
                $: 'jquery',
                jQuery: 'jquery',
                // Card: 'card' // Trying without this line first
            })
        ]
        ...
    }
