### ISSUE TITLE
Use with Stripe Elements

### ISSUE THREAD

**Issue by DivineOmega** [jessepollak/card#409]
Sorry, this is a bit of an open ended question: is it possible to use this library combined with Stripe Elements?

I can't seem to figure out a way to do so. I'm thinking I might need to use Stripe.js v2, but I'd like to hear other people's thoughts.

**Comment by tuun** [comment]
Hey @DivineOmega ,

Just realized that Stripe Elements loads within an Iframe, with an external src, so it can't be accessed with javascript.

Were you able to use another method?

**Comment by DivineOmega** [comment]
I'm sorry. The project I need to do this on was abandoned, so I did not look into it any further.
