### ISSUE TITLE
More prominent mention of Stripe jquery.payments

### ISSUE THREAD

**Issue by eoghanmurray** [jessepollak/card#419]
Hi, could you add a more prominent link to https://github.com/stripe/jquery.payment/ in the README to show that it is a dependency?  For my usecase I missed that that was the source of the card validation stuff and ended up implementing things on top of this library instead of that one.
(I'm also still confused as to how the 'Usage (without jQuery)' works given that payment is a jquery lib?)

**Comment by melloware** [comment]
it uses Payment.js from here: https://github.com/jessepollak/payment/blob/master/dist/payment.js

And its not a Jquery i]lib it doesn't look like?  I don't see jquery in its dependencies?
