### ISSUE TITLE
Card number limit (maxlength)

### ISSUE THREAD

**Issue by thiagok** [jessepollak/card#426]
Hi guys

Is it possible to set a maximum number of card number digits?  

Like "4111 1111 1111 1111" have 16 digits or 19 with whitespace.

Thanks!

**Comment by justinffortier** [comment]
@thiagok Did you ever come up with a solution for this?

**Comment by justinffortier** [comment]
A bit hacky, but this worked for me. You can just get the trimmed length of the credit card and if it's greater than or equal to 16 disable any key down actions except for backspace or delete. 

```
$('#cc-number').on('keydown', (e) => {
  const isBackSpace = e.keyCode === 8 || e.keyCode === 46
  const value = $('#cc-number').val()
  const creditCardValue = value.replace(/ /g, '')
  if (creditCardValue.length >= 16 && !isBackSpace) {
    return false
  }
})
```

**Comment by thiagok** [comment]
@justinffortier Thanks for the answer. I did something close here: 

$(".card-field #number").keydown(function(e) {
      if ((e.keyCode >= 48 && e.keyCode <= 57) || (e.keyCode >= 96 && e.keyCode <= 105)) {
        if (this.value.length > 18)
          e.preventDefault();
      }
});

Thanks!

**Comment by omansak** [comment]
```
      Payment.getCardArray().forEach(i => {
        i.length = [16];
      });
```

best way
