### ISSUE TITLE
Focus on text input when rendered part of card is clicked

### ISSUE THREAD

**Issue by Zakay** [jessepollak/card#43]
When clicking on card-number or other parts of the image, a focus on that text field would be nice. I found my self clicking there and it felt odd not being able to edit in-place.

Also when a text field is focused a highlight could be nice to have on the card itself.

**Comment by jessepollak** [comment]
I'm closing this issue as it's been stale for a while. If you'd like to open a PR with the change, I'd love to help in anyway I can!
