### ISSUE TITLE
how do we add this with vuejs??

### ISSUE THREAD

**Issue by ironshashi** [jessepollak/card#441]

**Comment by hvaughan3** [comment]
Try these links:
https://github.com/jessepollak/card/issues/365
https://github.com/jessepollak/card/issues/342

**Comment by kelanik8** [comment]
`
npm install --save card
var $ = require("jquery");
window.jQuery = $;
var card = require("card");

export default {
created() {
var card = new Card({
    form: 'form',
    container: '.card-wrapper',

    placeholders: {
        number: '**** **** **** ****',
        name: 'Arya Stark',
        expiry: '**/****',
        cvc: '***'
    }
});
}
}
`

**Comment by melloware** [comment]
README.MD has been updated for vue.js
