### ISSUE TITLE
Add slide-out as optional replacement for CVC card rotation

### ISSUE THREAD

**Issue by Zakay** [jessepollak/card#45]
I find that the 3d rotation is too grand. I would suggest another solution.
As soon as the form is recognizing a card which has CVC at the back.
The backside of the card will slide quickly into the image and "greyed", when user selects the CVC field, the front/back changes focus according to the image.

When entering card details you really want to disturb the user as little as possible as it can affect CR.

![suggestion](https://cloud.githubusercontent.com/assets/315159/3209872/8f5d1a7e-ee92-11e3-9e16-ce754191c12e.png)

**Comment by jessepollak** [comment]
As this has been stale for over a year, I'm closing the issue for now.

If you'd like to open a PR with the change, I'd love to support you in making that happen!
