### ISSUE TITLE
Spam in this repository ?

### ISSUE THREAD

**Issue by juancarlosso** [jessepollak/card#452]
Am i the only one receiving this ?

<img width="466" alt="Screen Shot 2020-02-27 at 15 53 06" src="https://user-images.githubusercontent.com/38847005/75492202-e326a980-597c-11ea-8888-77c2c32c6561.png">

**Comment by Darbotechub** [comment]
Same here...

**Comment by jessepollak** [comment]
I am seeing as well, but not sure what to do about it. Looks like Github is cleaning them up but only after emails are going out.

**Comment by juancarlosso** [comment]
Perhaps sending an email to the support account... i don't know... is an unusual situation.
