### ISSUE TITLE
Ability to replace card detection method

### ISSUE THREAD

**Issue by Zakay** [jessepollak/card#46]
Many payment providers have their own card detection and they get updated pretty often, this way the developer gets too choose to use their payment providers ones or built-in one.

**Comment by sebrojas14** [comment]
I'm with  @lipis

**Comment by Zakay** [comment]
With a detection callback a developer could go much further and detect issuing bank and display an even more correct view of that credit card. I already love that it shows Visa/AmEx etc, and the library shouldn't go much further, but adding an ability to override the detection method won't make the library more complex, it just adds a nice feature for those who want to go a step further and display local bank credit cards.

**Comment by jessepollak** [comment]
Hi all, thanks for your feedback! I like this idea, unfortunately, making the change requires a pretty big logic shift around how we do credit card detection. Right now, I don't have the bandwidth to make that change and there's not enough demand to motivate me to create that bandwidth.

I'm closing the issue for now. If you'd like to create a PR to make the change, I would *love* to support you in making that happen (especially if you've never contributed before). I'm always around to help answer questions.
