### ISSUE TITLE
 hire programmer

### ISSUE THREAD

**Issue by lucasoler** [jessepollak/card#460]
I would like to implement this style of card when checking out the plugin for wocoomerce 'PAGSEGURO do Cláudio Sanches'

The plugin is well documented, and for those who understand, it will be something simple, get in touch and give me the value for this service, thanks.

**Comment by mrfleap** [comment]
Hi, this probably isn't the best place to be posting about this, but I have experience using Card JS and a lot of experience with front end development. Shoot me an email on my profile and we'll see if I could help you out.
