### ISSUE TITLE
Mobile-Responsive breaking layout

### ISSUE THREAD

**Issue by gabrielcpolidoro** [jessepollak/card#463]
On devices with width less than 450px, the layout corrupts and the card goes "outside" of the screen.

In my situation, I've countered this issue with some CSS:

```
@media (max-width: 450px) {
  .card-wrapper {
    max-width: 80vw;
    width: 100%;
    margin: 20px auto;
    overflow-x: hidden;
  }

  .card-wrapper > .jp-card-container {
    transform: scale(0.625);
    transform-origin: left center;
  }
}
```

Not the best CSS in the world, but I think that can help someone facing the same situation.

**Comment by CliqLabs** [comment]
Just my 2 cents: I think this should get merged.  @gabrielcpolidoro Can you create a pull request for this?

**Comment by gabrielcpolidoro** [comment]
Of course! I'll create it as soon as a possible

**Comment by melloware** [comment]
@gabrielcpolidoro if you submit a PR I can merge it.

**Comment by turgayozgur** [comment]
Unfortunately, it is not possible to align the card image to the center with those properties. After disabling all of the properties above, it is working fine. How can I disable them on the code side?

**Comment by melloware** [comment]
Its CSS so you can't disable it with code simply override the CSS in your application.
