### ISSUE TITLE
Card number field should add space before adding the next digit.

### ISSUE THREAD

**Issue by Raza403** [jessepollak/card#474]
**Test Case:**
- Entering a Visa card number in the input field.
- When we add the 5th digit, space is added before the 5th digit.
- This space should be added just after we enter the fourth digit, this will be better user experience.
- You can see this implementation here https://cardjs.co.uk/

**Comment by melloware** [comment]
Please use version 2.5.0 mine is adding the space properly.  See: https://www.primefaces.org/showcase-ext/sections/creditcard/basicUsage.jsf
