### ISSUE TITLE
CSS Invalid

### ISSUE THREAD

**Issue by danielehrhardt** [jessepollak/card#481]
![image](https://user-images.githubusercontent.com/19570043/101375943-43555f00-38b0-11eb-9ae9-4ec75caee4bb.png)

**Comment by melloware** [comment]
@danielehrhardt can you try this latest version: https://github.com/jessepollak/card/tree/master/dist

**Comment by melloware** [comment]
I think it was fixed with this PR: https://github.com/jessepollak/card/pull/473

**Comment by danielehrhardt** [comment]
I think you have to update your npm package :)

**Comment by melloware** [comment]
Yep it hasn't been released to NPM yet.
