### ISSUE TITLE
Expiry date mask not working on mobile.

### ISSUE THREAD

**Issue by Enzodtz** [jessepollak/card#484]
### Description

Hi, 

I have the card working perfectly fine on Desktops (and even on the DevTools responsive layout tester). But going into a real mobile device, things don't work as expected.

When placing the card data, everything works fine, the data goes into the card image, the card flips when focusing the CVC, and etc. But when I try to place the expiry date, it just don't mask the input. 

### Example

When I type "1121" I would expect "11 / 21", same as desktop, but it just keeps the same as what was typed:

![image](https://user-images.githubusercontent.com/7780770/107259419-ba77b280-6a1b-11eb-9b1a-fd665d258f23.png)

(Of course that's not a real Credit Card, just to show that the data was typed before, but when testing with a real one, the error keeps the same)

### Code

```
$("#payment").card({
    container: ".card-wrapper",
    formSelectors: {
      numberInput: "#card-number", 
      expiryInput: "#card-expiry",
      cvcInput: "#card-cvv", 
      nameInput: "#card-name", 
    },
    width: $(".card-wrapper").width(),
    placeholders: {
      number: "•••• •••• •••• ••••",
      name: "Name",
      expiry: "••/••",
      cvc: "•••",
    },
  });
```

Looking at the DevTools (from the android tab), I got no console errors.

### Version 

I'm using the JQuery dist/jquery.card.js

### Conclusion

Because it worked in Desktop, maybe there should be some compatibility error? Is there something that I can do to fix this?

Thanks!

**Comment by melloware** [comment]
Try changing your input type for the Expiry to`input type="tel"` instead of `input type="text"`

**Comment by Enzodtz** [comment]
I did it, but the error keeps the same.

[If you want to try it](oticket.com.br/payment/card)

**Comment by melloware** [comment]
are you using the latest version of card 2.5.1 from the /dist folder here?

**Comment by Enzodtz** [comment]
Yes, I am, also the JQuery version is 3.5.1 not slim.
Can't it be a compatibility error?

**Comment by melloware** [comment]
Jquery does not matter as this lib does not use Jquery.

**Comment by Enzodtz** [comment]
Well, actually I'm using the `dist/jquery.card.js` JQuery version [(This version](https://github.com/jessepollak/card/blob/master/dist/jquery.card.js)

**Comment by melloware** [comment]
Ha that is NOT this library.  Its an ancient version of this library before they removed Jquery as a requirement.

**Comment by melloware** [comment]
Closing as invalid since that library is not this one.  Please upgrade to this library and set make sure to use the latest 2.5.1 version from this DIST folder.

**Comment by Enzodtz** [comment]
I was following the readme [JQuery Session](https://github.com/jessepollak/card#using-with-jquery)

**Comment by melloware** [comment]
OK your link to "If you want to try it" is broken it goes no where?

**Comment by Enzodtz** [comment]
Sorry, I forgot to add the `https://`, I've edited it and now it's working. The card code starts at line 31.

And I also changed the JQuery version to the normal version, and got the same results: 

- No console errors
- Everything working but the expiry on mobile

New code:

```
var card = new Card({
    form: "#payment",
    container: ".card-wrapper",
    formSelectors: {
      numberInput: "#card-number",
      expiryInput: "#card-expiry",
      cvcInput: "#card-cvv",
      nameInput: "#card-name",
    },
    width: $(".card-wrapper").width(),
    placeholders: {
      number: "•••• •••• •••• ••••",
      name: "Name",
      expiry: "••/••",
      cvc: "•••",
    },
  });
```

**Comment by melloware** [comment]
I am not seeing anything on that page for Credit Card?

**Comment by melloware** [comment]
no prob
