### ISSUE TITLE
credit card visa

### ISSUE THREAD

**Issue by 209626983** [jessepollak/card#510]
4/47/3243/69/9/9
4847832430298989

**Comment by melloware** [comment]
I am not sure what the problem is?

**Comment by 209626983** [comment]
![IMG_٢٠٢١٠٥٢٣_١٦٥٨٤٩](https://user-images.githubusercontent.com/84592535/119263732-ebee4580-bbe8-11eb-81da-d6ca0f259a27.jpg)
call by massage saudi arebian

**Comment by melloware** [comment]
Works fine for me..
![image](https://user-images.githubusercontent.com/4399574/119267711-c5ff7b80-bbbd-11eb-9bc6-cadc00b31e2c.png)
