### ISSUE TITLE
Minimum font sizes break credit card logos

### ISSUE THREAD

**Issue by Kwpolska** [jessepollak/card#52]
Chrome has this nifty little feature that it doesn’t allow fonts to go under a specific size (6pt is the minimum, the value is user-configurable; don’t remember the default setting though).  However, Discover and AmEx logos are broken by that, and look like crap (*network* in Discover is off-center; AmEx is a complete mess).

![image](https://cloud.githubusercontent.com/assets/327323/3230688/80111d76-f0a5-11e3-8b2f-9a4b26ec1e17.png)
![image](https://cloud.githubusercontent.com/assets/327323/3230692/8a9a4ea2-f0a5-11e3-9531-fe0433b0ed1f.png)

**Comment by jessepollak** [comment]
I'm closing this issue as it's been stale for a long time.

If you're still having this problem or you'd like to make a fix, let me know and I'd love to help you open up a pull request! I'm always around to help answer questions :)
