### ISSUE TITLE
Mastercard Not recognized

### ISSUE THREAD

**Issue by mauroagr** [jessepollak/card#526]
The Credit Card test from Mercado Pago brand (mastercard) not recognized
https://www.mercadopago.com.br/developers/pt/guides/online-payments/checkout-api/testing#bookmark_cart%C3%B5es_de_teste
5031 4332 1540 6351

How i can add this range in script.
Thanks
Mauro

**Comment by melloware** [comment]
Can you go here an try your number: https://www.primefaces.org/showcase-ext/sections/creditcard/basicUsage.jsf

According to the latest version your card is a Maestro card.

**Comment by mauroagr** [comment]
![image](https://user-images.githubusercontent.com/5348884/128702590-9594f312-cf94-4048-9a5a-18a996452152.png)

Recognized like a maestro. Can be a error documentation in Mercado Pago.
I will update the card.js.
Thanks
Mauro

**Comment by melloware** [comment]
Yep previously someone had reported that type as Maestro..

```
 {
      type: 'maestro',
      pattern: /^(50|5[6-9]|6007|6220|6304|6703|6708|6759|676[1-3])/,
      format: defaultFormat,
      length: [12..19],
      cvcLength: [3],
      luhn: true
  }
```

**Comment by mauroagr** [comment]
Yes, i think is a wrong text in mercado pago documentation.
Thanks
Mauro

**Comment by sheakhasan926** [comment]
Active card

**Comment by melloware** [comment]
> Active card

@sheakhasan926 I don't know what that means?

**Comment by sheakhasan926** [comment]
Active

**Comment by sheakhasan926** [comment]
True
