### ISSUE TITLE
Card Number Can't Be Blur In IOS When Input Card Numbers

### ISSUE THREAD

**Issue by PythonWongXb** [jessepollak/card#527]

**Comment by PythonWongXb** [comment]
Hi, our team fall in a huge trouble, can u do us a favor, guys?
Description : I find I can't be blur in Card Number Input.
When I want to focus in another input, It will still focus in the Card Number Input.


I think Maybe somethind wrong about the focus event. because I can on 'focus' event after I try to blur the Card Number Input. so I can't blur.

**Comment by melloware** [comment]
What version of Card are you using?

**Comment by zaxlct** [comment]
> What version of Card are you using?

I tested it. 2.5.3 and 2.4.0 will not work.

**Comment by sheakhasan926** [comment]
Card information number?

**Comment by sheakhasan926** [comment]
> > What version of Card are you using?
> 
> I tested it. 2.5.3 and 2.4.0 will not work.

**Comment by melloware** [comment]
is this your issue? https://github.com/jessepollak/payment/issues/161

**Comment by zaxlct** [comment]
> is this your issue? [jessepollak/payment#161](https://github.com/jessepollak/payment/issues/161)

Yes.Should I solve this issue quickly?

**Comment by melloware** [comment]
Yes I think you can update payment or I might need to release A new version of Card with this change.  I will do that tomorrow.

**Comment by PythonWongXb** [comment]
sir, I am using "card": "^2.4.0". 
It doesn't seem to have relation with payment

**Comment by melloware** [comment]
OK I just deployed Payment 2.4.5 to NPM https://www.npmjs.com/package/payment

Can you try again?

**Comment by melloware** [comment]
Card  2.5.4 is released: https://www.npmjs.com/package/card

**Comment by PythonWongXb** [comment]
it works, thanks.
 : )
