### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by kursadaydin42** [jessepollak/card#545]
Hello I'm working with Bootstrap 5 and I'm getting this error how do I solve it?

`card.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Function.e.removeClass (card.js:1)
    at Function.e.toggleClass (card.js:1)
    at t.toggleValidClass (card.js:1)
    at card.js:1
    at e (card.js:1)
    at r (card.js:1)
    at t.attachHandlers (card.js:1)
    at new t (card.js:1)
    at index.html:308`

At the very bottom I make such a creation.

<script>
		new Card({
			form: document.querySelector('form'),
			container: '.card-wrapper',
			// Default placeholders for rendered fields - optional
			placeholders: {
				number: '•••• •••• •••• ••••',
				name: 'AD SOYAD',
				expiry: '••/••',
				cvc: '•••'
			},

		});
	</script>

**Comment by melloware** [comment]
Please create a reproducer using CodeSandbox for example so we can see your problem.

**Comment by LinkinFox** [comment]
> Cree un reproductor utilizando CodeSandbox, por ejemplo, para que podamos ver su problema.

A mi me pasa exactamente lo mismo estoy usando boostrab 4.6. Estoy tratando de integrar a mi proyecto en laravel y me sale este error. No se como solucionarlo ya revise la documentación y estoy y lo hago como viene en el ejemplo.

<img width="1370" alt="card" src="https://user-images.githubusercontent.com/41913901/146501326-ce4c4396-ef94-406b-9319-c91824350128.png">

**Comment by kursadaydin42** [comment]
That's how I solved the problem, the problem was selective. form: document.It was querySelector('form'), I used it instead. form: "#krediKartiForm",

**Comment by melloware** [comment]
So can this be closed?

**Comment by LinkinFox** [comment]
Efectivamente el usuario @kursadaydin42 tiene razón gracias a tu ejemplo me pude dar cuenta de mi error. En la documentación no viene definido si "form" es un elemento o un identificador. Cometi el error de interpretarlo como elemento y por esa razón no estaba usando el identificador en el 'form'.

<img width="679" alt="1" src="https://user-images.githubusercontent.com/41913901/146602762-e96d7196-d701-4c12-997f-9217058abf56.png">

En esta imagen ambos codigos que estan en la flecha verde funcionan. El de color rojo no, pero como les comente aqui es interpretativo ya que yo llegue a pensar que esa parte del codigo se referia al elemento form, hay que actualizar la documentacion para colocar un "#" y asi se pueda entender que es un identificador.
<img width="935" alt="2" src="https://user-images.githubusercontent.com/41913901/146603239-990a7145-a0c2-431e-a4b9-4862a641cf5d.png">

Gracias por la respuesta @kursadaydin42 me sirvió mucho tu ayuda.

<img width="1034" alt="3" src="https://user-images.githubusercontent.com/41913901/146603489-81413a5c-a41c-49cd-b6cd-7b1ac4ef11f9.png">

@melloware considero que si se debe cerrar este caso ya que no es un bug.

**Comment by melloware** [comment]
Thanks I just fixed the README.MD
