### ISSUE TITLE
Allow for bypass of expiry format

### ISSUE THREAD

**Issue by joshlevinson** [jessepollak/card#58]
Some credit card processors require the expiry date to be in MMYY format.
This script forces the value to be MM/YY format. I realize that I could strip the slash before sending the value to the processor, but doing this is inconvenient.
Would it make sense to utilize a bypass option for this value's format?

**Comment by jessepollak** [comment]
I'm closing this issue as it's been stale for a while and I don't think the addition is in scope for Card's use case. Card should only be used a visual aid, if you'd like the data in a different form, you should access the individual inputs and format as necessary when you submit the form.

Thanks for reporting!
