### ISSUE TITLE
npm install errors 

### ISSUE THREAD

**Issue by FairyPenguin** [jessepollak/card#585]
I forked the repo and cloned it to my local and after I reach the step of run npm install I get this errors

```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
```
After that, I get a list of errors here is the complete log of this run (file)

[2022-12-02T02_28_13_317Z-debug-0.log](https://github.com/jessepollak/card/files/10137673/2022-12-02T02_28_13_317Z-debug-0.log)

**Comment by melloware** [comment]
OK I just fixed it with this PR: https://github.com/jessepollak/card/pull/586
Do a git pull again.

**Comment by melloware** [comment]
Yep you might have to do some work to update the webpack demo.  I updated all the dependencies and got the build working.

**Comment by FairyPenguin** [comment]
Errors are everywhere, and the project needs a lot of work to be updated and help others start contributing I fixed the Webpack problem and get the dev running and then faced a  [Cannot GET /] error, I tried many solutions but nothing succeed. 

`❰mahmoud❙~/Desktop/Python/HTML_CSS/Link Tree Profile/card(git≠✱master)❱✘≻ npm run development                     19:30:39

> card@2.5.4 development
> webpack-dev-server --hot

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.103:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/mahmoud/Desktop/Python/HTML_CSS/Link Tree Profile/card/public' directory
asset card.js 173 KiB [emitted] [minimized] (name: main) 1 related asset
runtime modules 27.3 KiB 13 modules
orphan modules 18.8 KiB [orphan] 8 modules
modules by path ./node_modules/ 215 KiB 32 modules
modules by path ./src/ 42.1 KiB
  ./src/coffee/card.coffee 12.6 KiB [built] [code generated]
  ./src/scss/card.scss 2.48 KiB [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./src/scss/card.scss 26.9 KiB [built] [code generated]
webpack 5.75.0 compiled successfully in 7382 ms

asset jquery.card.js 173 KiB [emitted] [minimized] (name: main) 1 related asset
runtime modules 27.3 KiB 13 modules
orphan modules 18.8 KiB [orphan] 8 modules
modules by path ./node_modules/ 215 KiB 32 modules
modules by path ./src/ 42.9 KiB
  modules by path ./src/coffee/*.coffee 13.5 KiB
    ./src/coffee/jquery.card.coffee 896 bytes [built] [code generated]
    ./src/coffee/card.coffee 12.6 KiB [built] [code generated]
  modules by path ./src/scss/*.scss 29.4 KiB
    ./src/scss/card.scss 2.48 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./src/scss/card.scss 26.9 KiB [built] [code generated]
external "jQuery" 42 bytes [built] [code generated]
webpack 5.75.0 compiled successfully in 7054 ms
`


![image](https://user-images.githubusercontent.com/37639473/205351863-ac4d6c93-8e3a-4d32-843f-f12b985bc60a.png)

**Comment by FairyPenguin** [comment]
At least if we can get the first steps working smoothly so we can focus on the main code, it will be great.

**Comment by melloware** [comment]
can you post what you did to get the webpack working or submit a PR?

**Comment by melloware** [comment]
OK i fixed it had to move `examples` directory to `public`  .  Do a git pull

**Comment by FairyPenguin** [comment]
> can you post what you did to get the webpack working or submit a PR?

Of course, I will do a PR, give me minutes 

and thankyou @melloware  for your patience and help.

**Comment by melloware** [comment]
I actually got it working so let me know if it works for you.

**Comment by FairyPenguin** [comment]
> I actually got it working so let me know if it works for you.

Yeah, it's working finally

I will work on the colors variables and do a PR
