### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by EslamElbyaly** [jessepollak/card#638]
Hi. I've created an HTML file using a notepad with the following code...
<head>
<script>
var card = new Card({
    form: '#myform', 
    container: '#con', 
    formSelectors: {
        numberInput: 'input#number'
}  
});
</script>
</head>
<body>
<div id="con">
<form id=myform>
<input type="text" name="number">
</form>
</div>

<script src="D:\card-master\dist\card.js">
</script>
</body>
- The result is just a text item. Nothing else!
- What am I missing?

**Comment by RupW** [comment]
Have you tried the example? You may need to change the path to the script.   
https://github.com/jessepollak/card/blob/2.5.4/example/index.html

Are there any errors in your browser console? Are you using card from npm or are you building a checkout from GitHub?

**Comment by ovicko** [comment]
Had similar issue, fixed by downloading the latest release
