### ISSUE TITLE
pleasss..

### ISSUE THREAD

**Issue by yoexyaa** [jessepollak/card#658]
how I can learn hack for credit card

**Comment by RupW** [comment]
If you mean to steal money, you can't do that. The credit card processors take this very seriously and have been working on defences, fraud detection and authentication mechanisms for years.

If you mean to steal other people's credit card details so you can steal their money, in an ideal world you wouldn't be able to do that either. But bugs happen. Don't do this.

**Comment by keparlak** [comment]
What a stupid question. I'm very curious where you got the courage to express that in the open world.
