### ISSUE TITLE
Card form reset.

### ISSUE THREAD

**Issue by shivareddy547** [jessepollak/card#86]
Hi, i have integrated card form inside the modal popup,when i click on cancel it should reset the form and card,here form values are resetting but color of card is not resetting to default.how we can reset the card and form Thanks in advance.

Thanks
Shiva.A

**Comment by alexfilatov** [comment]
this wasn't woking for me on 100% - card info remains on card figure when I did trick from the previous comment.
solved by following:

    $('.jp-card-number').html('•••• •••• •••• ••••');
    $('.jp-card-cvc').html('•••')
    $('.jp-card-name').html('CARD HOLDER')
    $('.jp-card-expiry').html('…')
