### ISSUE TITLE
Abstract CSS into separate project

### ISSUE THREAD

**Issue by lancecarlson** [jessepollak/card#87]
CSS into a separate project might make creating plugins for other libs/frameworks like Angular JS easier.

**Comment by jessepollak** [comment]
Thank you all for your feedback :)

I'm going to close this issue — it hasn't happened yet and I don't think I have the bandwidth the make it happen in the near future. Additionally, the CSS is very coupled to the JS/HTML and I'm not sure that it'd have additional utility as it's own project.

If anyone disagrees or would like to tackle this and open a PR, I would love to support you in making that happen. I'm always around to help or answer questions!
