### ISSUE TITLE
Improve font colour on unrecognized card type

### ISSUE THREAD

**Issue by jacorreia** [jessepollak/card#9]
You might want to change the colour of the font for better contrast when it can't recognize the card type.

Ie. if I type in a random number just to see how it works, I can barely see what I'm typing in on the card due to the lack of contrast.

**Comment by jessepollak** [comment]
Thanks for your feedback!

I'm closing as this issue has been stale for a while and the same effect can be achieved with custom styling outside of Card. If you'd like to work on a PR to make this happen, I'd love to support in any way I can :)
