### ISSUE TITLE
Allow over-ride of card type

### ISSUE THREAD

**Issue by naegelin** [jessepollak/card#93]
I suppose a common use case for this would be to be able to show users a stored card from a processor like Stripe which would return only a redacted version of their credit card. For instance:

Arya Stark
xxxx xxxx xxxx 4242
Exp: 05/2017
Type: Visa

Allowing you to pre-initialize the card with a type (and displaying Xs with the last 4) would facilitate this use case.

I would envision the initialization to look something like this:

                    // Default values for rendered fields - options
                    values: {
                        number: '•••• •••• •••• 4242}',
                        name: 'Arya Stark',
                        expiry: '05/2017',
                        cvc: '•••',
                        type:'visa'   
                    }

**Comment by mbhnyc** [comment]
:+1: on this

**Comment by jessepollak** [comment]
Thank you all for your feedback! I've created a general issue for this [here](https://github.com/jessepollak/card/issues/184) and will hopefully make it happen soon.
