### ISSUE TITLE
American Express card should not validate 3 digit CVC

### ISSUE THREAD

**Issue by johnbacon** [jessepollak/card#95]
In card.js and the visual representation of the credit card (three placeholder dots), American Express seems to accept a three digit CVC. I cannot find any documentation referencing a valid 3 digit CVC for American Express cards.

Should this be modified to accept only 4 digit values and should it be visually modified to match?

**Comment by stevemckenzie** [comment]
https://github.com/jessepollak/card/pull/181

**Comment by jessepollak** [comment]
There's a fix for this pending, so I'm closing this! Should ship in the next version (1.0.3).
