### ISSUE TITLE
Card gives off perception of sharing CC info to public

### ISSUE THREAD

**Issue by Madebym** [jessepollak/card#97]
Sorry if this is not the place to write about non-code stuff, but I just had my client say this to me after I added this great plugin to his website.

it's a really nice touch but I'm afraid that people will associate this with "giving card info to public"

I tried to explain to him that this is no way near giving any info to the public, but with no luck. Did anyone else had any similar experiences?

**Comment by jaxyeh** [comment]
@jessepollak - Sorry I had to brought this to your attention, we had experienced customer pissed off at us that "credit card can be licensed to use by anyone and is issued by Jesse Pollak". Initially, I had no idea what he was talking about until I tracked down this very particular hidden code in the CSS file:

```
content: \"This card has been issued by Jesse Pollak and is licensed for anyone to use anywhere for free.\\AIt comes with no warranty.\\A For support issues, please visit: github.com/jessepollak/card.\";\n
```

Earlier, I didn't know that this hidden message were shown on the back of the card when they place CCV numbers. This non-technical customer clearly doesn't understand this was a message was intent for the open-source licensed product known as "card", but it appeared that this non-technical customer translated it very differently toward his personal credit card. Just wanted to give you heads up that plugin appeared to be an issue to some of the customers and may be related to what @Madebym was talking about in related to "giving card info to public".

**Comment by jessepollak** [comment]
Thanks for all of the feedback all! I'm closing this issue for now, individual users will have to decide for themselves whether Card is a good fit for their use case :)

@jaxyeh if you'd like to change this, you can override the styling [here](https://github.com/jessepollak/card/blob/master/src/scss/card.scss#L239).
