### ISSUE TITLE
Add validation for multiple fields use case

### ISSUE THREAD

**Issue by amilajack** [jessepollak/card#98]
Is there a way to remove the "/" in the input, make them separate input fields and still make the animation work? I'm using stripe to submit my payment form and it doesn't accept the format 12/1996 etc. It needs separate fields like Month:12, Year: 1996. Is there a work around to this?

**Comment by cinghaman** [comment]
Validation for mm/yyyy would be nice to making sure that first its a proper year as i can enter 00/0000 and it still accepts + the epiry mm/yyyy is not less than current date

**Comment by takealuke** [comment]
Is it possible to use two <select> inputs for month/year? I'm trying it with no luck. . . The Card.js finds the <select> tags just fine. . . but when the values change it does not update the card. 

If not, can you advise on how to programmatically update the expiry? I tried creating a hidden text field. .  but no matter what event I trigger on that field, the card visual does not get updated.

**Comment by jessepollak** [comment]
This should work fine:
https://github.com/jessepollak/card#using-multiple-inputs-for-one-field.
