### ISSUE TITLE
Please Add JCB,Diners and UnionPay

### ISSUE THREAD

**Issue by ftkro** [jessepollak/card#99]
Because asia region  Most used brand.
or already available?
(I'm sorry, because it is Japanese, English is not well written.)

JCB Logo:http://partner.jcb.jp/brand/images/logo_img01.jpg
Diners Logo: https://www.diners.co.jp/ja/img/merchant/download/diners_logo_black.gif

**Comment by kimchakabuto** [comment]
#1000
